WIP - secure-ssh : check is users and groups exists before editing ssh config

diff --git a/scripts/auto-install b/scripts/auto-install
--- a/scripts/auto-install
+++ b/scripts/auto-install
@@ -6,10 +6,137 @@ networkCIDR="10.10.200.0/24"
 localhostIP="10.10.200.219"
 ## - VARIABLES
 
-rm /etc/apt/sources.list.d/pve-enterprise.list
+## ARGUMENTS
+vm_host=false
+proxmox=false
+hard_policy=false
+ssh_port=
+network_cidr=
+localhost_ip=
+bastion=
+allowed_users=
+allowed_groups=
+denied_users=
+denied_groups=
+## - ARGUMENTS
 
-echo '# Proxmox community package repository' >> /etc/apt/sources.list
-echo 'deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription' >> /etc/apt/sources.list
+CheckMandatoryParams() {
+	printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
+	# Vérification des paramètres obligatoires
+	printf "${c__fctAction}Checking for ssh parameter ...${nocolor}\n"
+	if [[ -z $ssh_port ]]; then
+		printf "${c__error}parameter ${c__msgVar}--sshport${c__error} is mandatory.${nocolor}\n"
+		exit 1
+	else
+		printf "${c__fct2}SSH Port : ${c__value}${ssh_port}${nocolor}\n"
+	fi
+
+	printf "${c__fctAction}Checking for network IP/CIDIR parameter ...${nocolor}\n"
+	if [[ -z $network_cidr ]]; then
+		printf "${c__error}parameter ${c__msgVar}--networkcidr${c__error} is mandatory.${nocolor}
+		\n"
+		exit 1
+	else
+		printf "${c__fct2}network IP/CIDIR : ${c__value}${network_cidr}${nocolor}\n"
+	fi
+
+	printf "${c__fctAction}Checking for network IP/CIDIR parameter ...${nocolor}\n"
+	if [[ -z $network_cidr ]]; then
+		printf "${c__error}parameter ${c__msgVar}--networkcidr${c__error} is mandatory.${nocolor}
+		\n"
+		exit 1
+	else
+		printf "${c__fct2}network IP/CIDIR : ${c__value}${network_cidr}${nocolor}\n"
+	fi
+
+	printf "${c__fctAction}Checking for network IP/CIDIR parameter ...${nocolor}\n"
+	if [[ -z $network_cidr ]]; then
+		printf "${c__error}parameter ${c__msgVar}--networkcidr${c__error} is mandatory.${nocolor}
+		\n"
+		exit 1
+	else
+		printf "${c__fct2}network IP/CIDIR : ${c__value}${network_cidr}${nocolor}\n"
+	fi
+
+	printf "${c__fctAction}Checking for network IP/CIDIR parameter ...${nocolor}\n"
+	if [[ -z $network_cidr ]]; then
+		printf "${c__error}parameter ${c__msgVar}--networkcidr${c__error} is mandatory.${nocolor}
+		\n"
+		exit 1
+	else
+		printf "${c__fct2}network IP/CIDIR : ${c__value}${network_cidr}${nocolor}\n"
+	fi
+	printf "\n${c__success}Mandatory parameters OK${nocolor}
+	\n"
+}
+## -----------------------------------------------------------------------
+# CheckIfRoot
+StartText
+# Récupération des paramètres en utilisant getopts
+while [[ $# -gt 0 ]]; do
+  case $1 in
+	--vm)
+	  shift
+	  vm_host=true
+	  ;;
+	--proxmox)
+	  shift
+	  proxmox=true
+	  ;;
+    -s | --sshport)
+      shift
+      ssh_port=$1
+      ;;
+    -n | --networkcidr)
+      shift
+      network_cidr=$1
+      ;;
+	-l | --localhostIP)
+	  shift
+	  localhost_ip=$1
+	  ;;
+	-b | --bastion)
+	  shift
+	  bastion=$1
+	  ;;
+    -u | --allowedusers)
+      shift
+    #   allowed_users=($(echo "$1" | tr ',' ' '))
+      allowed_users=$1
+      ;;
+    -g | --allowedgroups)
+      shift
+    #   allowed_groups=($(echo "$1" | tr ',' ' '))
+      allowed_groups=$1
+      ;;
+    -U | --deniedusers)
+      shift
+    #   denied_users=($(echo "$1" | tr ',' ' '))
+      denied_users=$1
+      ;;
+    -G | --deniedgroups)
+      shift
+    #   denied_groups=($(echo "$1" | tr ',' ' '))
+      denied_groups=$1
+      ;;
+    -h | --help)
+	HowToUse
+	exit 0
+		;;
+	*)
+      echo "Option invalide: $1"
+      exit 1
+      ;;
+  esac
+  shift
+done
+
+if [[ $proxmox == true ]]; then
+	mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.disabled
+
+	echo '# Proxmox community package repository' >> /etc/apt/sources.list
+	echo 'deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription' >> /etc/apt/sources.list
+fi
 
 apt update
 apt upgrade
@@ -17,12 +144,18 @@ apt dist-upgrade
 
 apt install htop gzip
 
-adduser alex
-# usermod -aG adm alex
-usermod -aG sudo alex
-
-## ssh config
-
 
 ## start scripts
-bash iptables-for-proxmox $sshPort $networkCIDR $localhostIP
+if [ $proxmox == true ]; then
+	if [ $vm_host == false ]; then
+		bash iptables-for-proxmox $ssh_port $network_cidr
+	else
+		printf "can't apply both --vm and --proxmox adding rules"
+	fi
+elif [ $vm_host == true ]; then
+	bash iptables-for-vm $ssh_port $network_cidr $localhost_ip
+fi
+
+bash init-users -u $allowed_users -g $allowed_groups -U $denied_users -G $denied_groups
+
+bash secure-ssh -p $ssh_port -n $network_cidr -u $allowed_users -g $allowed_groups -U $denied_users -G $denied_groups
diff --git a/scripts/iptables-proxmox b/scripts/iptables-proxmox
--- a/scripts/iptables-proxmox
+++ b/scripts/iptables-proxmox
@@ -3,38 +3,213 @@
 ## * 🚧 TODO
 #  * - bastion : rebond avec interfaces entrée / sortie
 
+############
+## COLORS ##
+############
+nocolor='\033[0m'
+whiite='\033[0;97m'
+whiitebold='\033[0;1;97m'
+purple='\033[0;38;5;201m'
+blue='\033[0;38;5;45m'
+blueblink='\033[0;5;38;5;45m'
+darkblue='\033[0;38;5;27m'
+green='\033[0;32m'
+greendim='\033[0;3;32m'
+yellow='\033[0;38;5;178m'
+orange='\e[38;5;166;3m'
+orangeital='\e[0;3;38;5;166m'
+gray='\033[0;38;5;249m'
+graybold='\033[0;1;38;5;249m'
+graydim='\033[0;2;38;5;250m'
+red='\033[0;91m'
+## CUSTOM
+# c__fctName='\033[0;38;5;45m'
+c__fctName=$whiitebold
+c__fctAction=$graydim
+c__fct2=$gray
+c__msgVar=$graybold
+c__value=$blue
+c__error=$red
+c__success=$green
+
+
+###############
+## PARAMETERS
+###############
+commandPath=$0
+commandName=`basename "$commandPath"`
+pwd=$(pwd)
+actualpwd=$(pwd)
+
+##############
 ## ARGUMENTS
-# $1 : IP address
-# $2 : Port
-sshPort=$1
-networkCIDR=$2
-localhostIP=$3
-hostIP=$4
+##############
+ssh_port=
+network_host=
+network_vm=
+bastion=
 
-# Check if sshPort not empty
-if [ -z "$sshPort" ]; then
-	printf "ERROR: sshPort is empty\n";
-	exit 1;
-fi
+CheckIptables() {
+	# Vérification des paramètres obligatoires
+	printf "${c__fctAction}Checking iptables ...${nocolor}\n"
+	if [[ -z $ssh_port ]]; then
+		printf "${c__error}iptables not found${nocolor}
+		\n"
+		exit 1
+	else
+		printf "${c__fct2}iptables found${nocolor}\n"
+	fi
+}
 
-if [ -z "$networkCIDR" ]; then
-	printf "ERROR: networkCIDR is empty\n";
-	exit 1;
-fi
+CheckMandatoryParams() {
+	printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
 
-# Check if localhostIP not empty
-if [ -z "$localhostIP" ]; then
-	printf "ERROR: localhostIP is empty\n";
-	exit 1;
-fi
+	# Vérification des paramètres obligatoires
+	printf "${c__fctAction}Checking for SSH Port ...${nocolor}\n"
+	if [[ -z $ssh_port ]]; then
+		printf "${c__error}parameter ${c__msgVar}-s | --sshport${c__error} is mandatory.${nocolor}
+		\n"
+		exit 1
+	else
+		printf "${c__fct2}SSH Port : ${c__value}${ssh_port}${nocolor}\n"
+	fi
 
-# rules for ping
-iptables -t filter -A INPUT -p icmp -j ACCEPT
-iptables -t filter -A OUTPUT -p icmp -j ACCEPT
+	printf "${c__fctAction}Checking for host network ...${nocolor}\n"
+	if [[ -z $network_host ]]; then
+		printf "${c__error}parameter ${c__msgVar}-n | --network-host${c__error} is mandatory.${nocolor}
+		\n"
+		exit 1
+	else
+		printf "${c__fct2}host network : ${c__value}${network_host}${nocolor}\n"
+	fi
 
-iptables -I INPUT -p tcp --dport $sshPort -j DROP
-iptables -I INPUT -s $networkCIDR -p tcp --dport $sshPort -j ACCEPT
+	# printf "${c__fctAction}Checking for VMs network ...${nocolor}\n"
+	# if [[ -z $network_vm ]]; then
+	# 	printf "${c__error}parameter ${c__msgVar}-n | --network-vm${c__error} is mandatory.${nocolor}
+	# 	\n"
+	# 	exit 1
+	# else
+	# 	printf "${c__fct2}VMs network : ${c__value}${network_vm}${nocolor}\n"
+	# fi
 
-# si une machine établie une connexion, on laisser passer la communication
-# iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-# iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
+	# printf "${c__fctAction}Checking for localhost IP ...${nocolor}\n"
+	# if [[ -z $localhostIP ]]; then
+	# 	printf "${c__error}parameter ${c__msgVar}-i | --localhostIP${c__error} is mandatory.${nocolor}
+	# 	\n"
+	# 	exit 1
+	# else
+	# 	printf "${c__fct2}localhostIP : ${c__value}${localhostIP}${nocolor}\n"
+	# fi
+
+	printf "\n${c__success}Mandatory parameters OK${nocolor}
+	\n"
+}
+
+
+ManageICMP(){
+	printf "${c__fctName}Adding ICMP rule ...${nocolor}\n"
+	# rules for ping
+	iptables > /dev/null
+	if [[ $? -eq 0 ]]; then
+		iptables -t filter -A INPUT -p icmp -j ACCEPT
+		iptables -t filter -A OUTPUT -p icmp -j ACCEPT
+	else
+		printf "${c__error}iptables not found${nocolor}
+		\n"
+		exit 1
+	fi
+	
+	printf "\n${c__success}ICMP rules added${nocolor}
+	\n"
+}
+
+ManageSSH(){
+	printf "${c__fctName}Adding SSH rule for ${blue}${network_host}:${ssh_port}${c__funcName} ...${nocolor}\n"
+
+	iptables > /dev/null
+	if [[ $? -eq 0 ]]; then
+		iptables -I INPUT -p tcp --dport $ssh_port -j DROP
+		iptables -I INPUT -s $network_host -p tcp --dport $ssh_port -j ACCEPT
+	else
+		printf "${c__error}iptables not found${nocolor}
+		\n"
+		exit 1
+	fi
+
+	printf "\n${c__success}SSH rules added${nocolor}
+	\n"
+}
+
+# ManageResponse(){
+# 	# si une machine établie une connexion, on laisser passer la communication
+# 	# iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
+# 	# iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
+# }
+
+
+
+StartText () {
+clear
+printf "${blue}$commandName${whiitebold} script ${nocolor}
+
+${whiitebold}This script is used to configure iptables on PROXMOX server.
+
+${yellow}🚨 By default, PROXMOX allow ssh connection from local network.
+${nocolor}\n"
+}
+HowToUse() {
+printf "❓ ${blue}How to use${gray}
+
+${commandName} -p 2222 -n 192.168.0.1/24 -u username1,sshuser@ip:port -g group1,group2 -U username3,sshuser@ip:port -G group4${nocolor}
+
+${whiitebold}Parameters :${gray}
+    -p  --sshport      : SSH port
+    -h  --network-host : host network
+    -v  --network-vm   : VMs Network
+    -b  --bastion   : Bastion, to connect to VMs
+${nocolor}\n"
+}
+
+## ------------------------------------------------------------------------------------------------------------------------------------ ##
+
+# CheckIfRoot
+StartText
+
+CheckIptables
+
+# Récupération des paramètres en utilisant getopts
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    -p | --sshport)
+      shift
+      ssh_port=$1
+      ;;
+    -h | --network-host)
+      shift
+      network_host=$1
+      ;;
+    -v | --network-vm)
+      shift
+      network_vm=$1
+      ;;
+	-b | --bastion)
+	  shift
+	  bastion=$1
+	  ;;
+    --help)
+	HowToUse
+	exit 0
+		;;
+	*)
+      echo "Option invalide: $1"
+      exit 1
+      ;;
+  esac
+  shift
+done
+
+CheckMandatoryParams
+
+ManageICMP
+ManageSSH
+# ManageResponse
diff --git a/scripts/secure-ssh b/scripts/secure-ssh
--- a/scripts/secure-ssh
+++ b/scripts/secure-ssh
@@ -1,93 +1,134 @@
 #!/bin/bash
 
+############
+## COLORS ##
+############
+nocolor='\033[0m'
+whiite='\033[0;97m'
+whiitebold='\033[0;1;97m'
+purple='\033[0;38;5;201m'
+blue='\033[0;38;5;45m'
+blueblink='\033[0;5;38;5;45m'
+darkblue='\033[0;38;5;27m'
+green='\033[0;32m'
+greendim='\033[0;3;32m'
+yellow='\033[0;38;5;178m'
+orange='\e[38;5;166;3m'
+orangeital='\e[0;3;38;5;166m'
+gray='\033[0;38;5;249m'
+graybold='\033[0;1;38;5;249m'
+graydim='\033[0;2;38;5;250m'
+red='\033[0;91m'
+## CUSTOM
+# c__fctName='\033[0;38;5;45m'
+c__fctName=$whiitebold
+c__fctAction=$graydim
+c__fct2=$gray
+c__msgVar=$graybold
+c__value=$blue
+c__error=$red
+c__success=$green
+
+
+###############
+## PARAMETERS
+###############
+commandPath=$0
+commandName=`basename "$commandPath"`
+pwd=$(pwd)
+actualpwd=$(pwd)
+
+
+##############
 ## VARIABLES
-sshd_config="files/etc/ssh/sshd_config"
+##############
+sshd_config="../files/etc/ssh/sshd_config"
 PWD=$(pwd)
 
 
-# Check if the script is being run with root privileges
-# if [ "$EUID" -ne 0 ]; then
-#     echo "Please run this script as root."
-#     exit 1
-# fi
-
-# Récupération des paramètres en utilisant getopts
-while [[ $# -gt 0 ]]; do
-  case $1 in
-    --allowedusers)
-      shift
-      allowed_users=($(echo "$1" | tr ',' ' '))
-      ;;
-    --allowedgroups)
-      shift
-      allowed_groups=($(echo "$1" | tr ',' ' '))
-      ;;
-    --deniedusers)
-      shift
-      denied_users=($(echo "$1" | tr ',' ' '))
-      ;;
-    --deniedgroups)
-      shift
-      denied_groups=($(echo "$1" | tr ',' ' '))
-      ;;
-    --sshport)
-      shift
-      ssh_port=$1
-      ;;
-    --networkcidr)
-      shift
-      network_cidr=$1
-      ;;
-    *)
-      echo "Option invalide: $1"
-      exit 1
-      ;;
-  esac
-  shift
-done
+CheckIfRoot() {
+	if [ "$EUID" -ne 0 ]; then
+	    printf "${red}Please run this script as root.${nocolor}\n"
+	    exit 1
+	fi
+}
 
 CheckMandatoryParams() {
+	printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
 	# Vérification des paramètres obligatoires
+	printf "${c__fctAction}Checking for ssh parameter ...${nocolor}\n"
 	if [[ -z $ssh_port ]]; then
-		echo "Le paramètre --sshport est obligatoire."
+		printf "${c__error}parameter ${c__msgVar}--sshport${c__error} is mandatory.${nocolor}\n"
 		exit 1
+	else
+		printf "${c__fct2}SSH Port : ${c__value}${ssh_port}${nocolor}\n"
 	fi
 
+	printf "${c__fctAction}Checking for network IP/CIDIR parameter ...${nocolor}\n"
 	if [[ -z $network_cidr ]]; then
-		echo "Le paramètre --networkcidr est obligatoire."
+		printf "${c__error}parameter ${c__msgVar}--networkcidr${c__error} is mandatory.${nocolor}
+		\n"
 		exit 1
+	else
+		printf "${c__fct2}network IP/CIDIR : ${c__value}${network_cidr}${nocolor}\n"
 	fi
+	printf "\n${c__success}Mandatory parameters OK${nocolor}
+	\n"
 }
 
 
-DisplayValues() {
-	## Affichage values
+CheckUsersAndGroups() {
+	# check if username contained in allowed_users array are valid
+	echo "allowed_users"
+	for allow_user in "${allowed_users[*]}"
+	do
+		echo "$allow_user"
+	done
+}
+
+
+
+ManageAllowUsers() {
+	printf "${c__fctName}Manage allowed users ...${nocolor}\n"
 	# Configuration des utilisateurs autorisés
 	if [[ ${#allowed_users[@]} -gt 0 ]]; then
-		echo "AllowUsers ${allowed_users[*]}"
+		bash ./update-ssh-config -k AllowUsers -v "${allowed_users[*]}"
+	else
+		printf "${c__fctAction}No allowed users to add${nocolor}\n"
 	fi
-
-	# Configuration des groupes autorisés
-	if [[ ${#allowed_groups[@]} -gt 0 ]]; then
-		echo "AllowGroups ${allowed_groups[*]}"
-	fi
-
-	# Configuration des utilisateurs non-autorisés
-	if [[ ${#denied_users[@]} -gt 0 ]]; then
-		echo "DenyUsers ${denied_users[*]}"
-	fi
-
-	# Configuration des groupes non-autorisés
-	if [[ ${#denied_groups[@]} -gt 0 ]]; then
-		echo "DenyGroups ${denied_groups[*]}"
-	fi
-
-	# Configuration du port SSH
-	echo "Port $ssh_port"
-
-	# Configuration du CIDR réseau
-	echo "ListenAddress $network_cidr"
+	printf "\n"
 }
+ManageAllowGroups() {
+	printf "${c__fctName}Manage allowed groups ...${nocolor}\n"
+	# Configuration des utilisateurs autorisés
+	if [[ ${#allowed_groups[@]} -gt 0 ]]; then
+		bash ./update-ssh-config -k AllowGroups -v "${allowed_groups[*]}"
+	else
+		printf "${c__fctAction}No allowed groups to add${nocolor}\n"
+	fi
+	printf "\n"
+}
+ManageDeniedUsers() {
+	printf "${c__fctName}Manage denied users ...${nocolor}\n"
+	# Configuration des utilisateurs autorisés
+	if [[ ${#denied_users[@]} -gt 0 ]]; then
+		bash ./update-ssh-config -k DenyUsers -v "${denied_users[*]}"
+	else
+		printf "${c__fctAction}No denied users to add${nocolor}\n"
+	fi
+	printf "\n"
+}
+ManageDeniedGroups() {
+	printf "${c__fctName}Manage denied groups ...${nocolor}\n"
+	# Configuration des utilisateurs autorisés
+	if [[ ${#denied_group[@]} -gt 0 ]]; then
+		bash ./update-ssh-config -k DenyGroups -v "${denied_group[*]}"
+	else
+		printf "${c__fctAction}No denied groups to add${nocolor}\n"
+	fi
+	printf "\n"
+}
+
 
 
 SavePreviousFile() {
@@ -109,3 +150,83 @@ UpdateConfig() {
 DisplayConfig() {
 	cat "$sshd_config"
 }
+
+
+StartText () {
+clear
+printf "🔐 ${blue}$commandName script ${nocolor}🔐
+
+${whiitebold}This script is made for easily configure .bashrc
+Get a prettier shell than the default one 😎
+Follow the next steps to configure it !${nocolor}
+\n"
+}
+HowToUse() {
+printf "❓ ${blue}How to use${gray}
+
+${commandName} -p 2222 -n 192.168.0.1/24 -u username1,sshuser@ip:port -g group1,group2 -U username3,sshuser@ip:port -G group4${nocolor}
+
+${whiitebold}Parameters :${gray}
+    -p  --sshport       : SSH port
+    -n  --networkcidr   : Network CIDR
+    -u  --allowedusers  : Allowed users to connect through SSH
+    -g  --allowedgroups : Allowed groups to connect through SSH
+    -U  --deniedusers   : Denied users to connect through SSH
+    -G  --deniedgroups  : Denied groups to connect through SSH
+    -h  --help          : show this message
+${nocolor}\n"
+}
+
+## ------------------------------------------------------------------------------------------------------------------------------------ ##
+
+# CheckIfRoot
+StartText
+# Récupération des paramètres en utilisant getopts
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    -p | --sshport)
+      shift
+      ssh_port=$1
+      ;;
+    -n | --networkcidr)
+      shift
+      network_cidr=$1
+      ;;
+    -u | --allowedusers)
+      shift
+      allowed_users=($(echo "$1" | tr ',' ' '))
+      ;;
+    -g | --allowedgroups)
+      shift
+      allowed_groups=($(echo "$1" | tr ',' ' '))
+      ;;
+    -U | --deniedusers)
+      shift
+      denied_users=($(echo "$1" | tr ',' ' '))
+      ;;
+    -G | --deniedgroups)
+      shift
+      denied_groups=($(echo "$1" | tr ',' ' '))
+      ;;
+    -h | --help)
+	HowToUse
+	exit 0
+		;;
+	*)
+      echo "Option invalide: $1"
+      exit 1
+      ;;
+  esac
+  shift
+done
+
+# CheckMandatoryParams
+
+CheckUsersAndGroups
+
+# ManageAllowUsers
+# ManageAllowGroups
+# ManageDeniedUsers
+# ManageDeniedGroups
+
+exit 0
diff --git a/scripts/update-ssh-config b/scripts/update-ssh-config
--- a/scripts/update-ssh-config
+++ b/scripts/update-ssh-config
@@ -19,49 +19,113 @@ gray='\033[0;38;5;249m'
 graybold='\033[0;1;38;5;249m'
 graydim='\033[0;2;38;5;250m'
 red='\033[0;91m'
+## CUSTOM
+c__fctName='\033[0;38;5;45m'
+c__fctAction=$graydim
+c__fct2=$gray
+c__msgVar=$graybold
+c__value=$green
+c__error=$red
+c__success=$green
 
 ################
 ## PARAMETERS ##
 ################
 commandPath=$0
 commandName=`basename "$commandPath"`
-
-sshd_path="/usr/sbin/sshd"
-ssh_config_file="files/etc/ssh/sshd_config"
-
+ARG_FILE="../files/etc/ssh/sshd_config"
 ARG_KEY=
 ARG_VALUE=
+
+
+##############
+## VARIABLES 
+##############
+sshd_path="/usr/sbin/sshd"
+runningAsRoot=false
+sshdExists=false
+syntaxStatus='invalid'
+verbose=false
+
 
 
 ###############
 ## FUNCTIONS ##
 ###############
+CheckMandatoryParams() {
+	if [[ $verbose = true ]]; then
+		printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
+	fi
+
+	# if [[ $verbose = true ]]; then
+	# 	printf "${c__fctAction}Checking for file parameter ...${nocolor}\n"
+	# fi
+	# if [[ -z $ARG_FILE ]]; then
+	# 	# printf "${c__error}ssh config file is mandatory.${nocolor}\n"
+	# 	printf "${c__error}parameter ${c__msgVar}-f | --file${c__error} is mandatory.${nocolor}\n"
+	# 	exit 1
+	# else
+	# 	printf "${c__fct2}file : ${c__value}${ARG_FILE}${nocolor}\n"
+	# fi
+
+	if [[ $verbose = true ]]; then
+		printf "${c__fctAction}Checking for key parameter ...${nocolor}\n"
+	fi
+	
+	if [[ -z $ARG_KEY ]]; then
+		printf "${c__error}parameter ${c__msgVar}-k | --key${c__error} is mandatory.${nocolor}\n"
+		exit 1
+	else
+
+		if [[ $verbose = true ]]; then
+			printf "${c__fct2}key : ${c__value}${ARG_KEY}${nocolor}\n"
+		fi
+	fi
+
+
+	if [[ $verbose = true ]]; then
+		printf "${c__fctAction}Checking for value parameter ...${nocolor}\n"
+	fi
+
+	if [[ -z $ARG_VALUE ]]; then
+		printf "${c__error}parameter ${c__msgVar}-v | --value${c__error} is mandatory.${nocolor}\n"
+		exit 1
+	else
+		
+		if [[ $verbose = true ]]; then
+			printf "${c__fct2}value : ${c__value}${ARG_VALUE}${nocolor}\n"
+		fi
+	fi
+}
+
 
 # Function to validate the syntax of a configuration key
 validate_key_syntax() {
     local key=$1
     local value=$2
-
-    # # Check if /usr/sbin/sshd exists
-    # if ! command -v "$sshd_path" >/dev/null; then
-    #     printf "${orange}Cannot validate syntax. ${sshd_path} not found.${nocolor}\n"
-    #     return 1
-    # fi
-
+	syntaxStatus='invalid'
     # Use sshd to check if the syntax is valid
     # $sshd_path -t -f /dev/null -o "${key} ${value}" 2>&1
-	# $sshd_path -t -F "$ssh_config_file" -fN
+	# $sshd_path -t -F "$ARG_FILE" -fN
+	if [ "$runningAsRoot" = true ] && [`$sshdExists` = true ]; then
 	printf "${orange}"
-	sudo $sshd_path -f "$ssh_config_file" -o "${key} ${value}" 2>&1
+	sudo $sshd_path -f "$ARG_FILE" -o "${key} ${value}" 2>&1
 
-    # Check the return code of the sshd command
-    if [ $? -eq 0 ]; then
-        # printf "${graybold}\"${key}\"${green} is a valid parameter.${nocolor}\n"
-        return 0
-    else
-        printf "${graybold}\"${key}\"${red} is not a valid parameter.${nocolor}\n"
-        return 1
-    fi
+		# Check the return code of the sshd command
+		if [ $? -eq 0 ]; then
+			printf "${graybold}\"${key}\"${green} is a valid parameter.${nocolor}\n"
+			syntaxStatus='valid'
+			return 0
+		else
+			printf "${graybold}\"${key}\"${red} is not a valid parameter.${nocolor}\n"
+			syntaxStatus='invalid'
+			return 1
+		fi
+	else
+		# printf "${orange}Cannot validate syntax. ${sshd_path} not found.${nocolor}\n"
+		syntaxStatus='unknown'
+		return 2
+	fi
 }
 
 # Function to update a specific configuration value
@@ -69,20 +133,33 @@ update_sshd_config() {
     local key=$1
     local value=$2
 
-	# Validate the syntax of the key and value
-    validate_key_syntax "$key" "$value"
-    if [ $? -ne 0 ]; then
-        printf "${graydim}Cancel update.${nocolor}\n"
-        return
-    fi
-
 	# Use sed to find and replace the configuration line, even if it's commented out
-	sed -i "s/^#\?\s*${key}\s*.*/${key} ${value}/" "$ssh_config_file"
+	sed -i "s/^#\?\s*${key}\s*.*/${key} ${value}/" "$ARG_FILE"
+	sedResult=$?
 	# Check if the sed command was successful
-	if [ $? -eq 0 ]; then
-		printf "${gray}Updated ${darkblue}${key}${gray} to ${purple}${value}${gray} in ${graybold}${ssh_config_file}${nocolor}\n"
+	if [ $sedResult -eq 0 ]; then
+
+		# Check if the sed command added a new line
+		if ! grep -q "${key} ${value}" "$ARG_FILE"; then
+			printf "${gray}Key not found.${graydim}${ARG_FILE}${nocolor}\n"
+
+			if [ $syntaxStatus = 'unknown' ]; then
+				printf "\n# TO VALIDATE\n${key} ${value}\n" >> "$ARG_FILE"
+			elif [ $syntaxStatus = 'valid' ]; then
+				printf "\n${key} ${value}\n" >> "$ARG_FILE"
+			else
+				printf "${red}synthax invalid${nocolor}\n"
+				exit 1
+			fi
+
+			printf "${green}Add${gray} - Set ${blue}${key} ${purple}${value}${nocolor}\n"
+		else 
+			printf "${yellow}Update${gray} - Set ${blue}${key} ${purple}${value}${gray} ${graydim}${ARG_FILE}${nocolor}\n"
+		fi
+
 	else
-		printf "${orangeital}Failed to update ${key}${nocolor}\n"
+		printf "${red}Failed to update ${key}${nocolor}\n"
+		exit 1
 	fi
 }
 
@@ -91,10 +168,11 @@ update_sshd_config() {
 #############
 
 StartText () {
-    printf "\n${blue}This script is made for updating SSH configuration${nocolor}\n"
+    printf "${blue}$commandName script${nocolor}
+${whiitebold}This script is made for updating SSH configuration${nocolor}\n"
 }
 HowToUse () {
-printf "\n${darkblue}How to use ?${gray}
+printf "\n❓ ${blue}How to use${gray}
 ${white}${commandName} -k <key> -v <value>${nocolor}\n"
 }
 
@@ -103,22 +181,26 @@ ${white}${commandName} -k <key> -v <value>${nocolor}\n"
 #####
 
 # Check if the script is being run with root privileges
-if [ "$EUID" -ne 0 ]; then
-    printf "${red}Please run this script as root.${nocolor}\n"
-    exit 1
-fi
-
-# Check if ssh_config file exists
-if [ ! -f "$ssh_config_file" ]; then
-	printf "${red}sshd_config file not found at ${whiitebold}"${ssh_config_file}"${red}${nocolor}\n"
-	exit 1;
-fi
+# if [ "$EUID" -ne 0 ]; then
+#     printf "${red}Please run this script as root.${nocolor}\n"
+#     exit 1
+# else
+#    runningAsRoot=true
+# fi
 
 # Check if sshd exists
-if ! command -v "$sshd_path" >/dev/null; then
-	printf "${red}Service ${whiitebold}"${sshd_path}"${red} not found.${nocolor}\n"
-	exit 1
-fi
+# if ! command -v "$sshd_path" >/dev/null; then
+# 	printf "${red}Service ${whiitebold}"${sshd_path}"${red} not found.${nocolor}\n"
+# 	exit 1
+# else
+# 	sshdExists=true
+# fi
+
+if [[ $# -le 0 ]]; then
+	commandName=$0
+else
+	commandName="ssh-config"
+fi 
 
 # Récupération des paramètres en utilisant getopts
 while [[ $# -gt 0 ]]; do
@@ -131,27 +213,38 @@ while [[ $# -gt 0 ]]; do
 			shift
 			ARG_VALUE=$1
 			;;
-		*)
+		-f | --file)
+			shift
+			ARG_FILE=$1
+			;;
+		-h | --help)
 			StartText
 			HowToUse
-			# echo "Option invalide: $1"
+			exit 0
+			;;
+		--verbose)
+			verbose=true
+			;;
+		*)
+			echo "$commandName - Option invalide: $1"
 			exit 1
 			;;
   	esac
   	shift
 done
 
-# Vérification des paramètres obligatoires
-if [[ -z $ARG_KEY ]]; then
-  printf "${red}Le paramètre -k | --key est obligatoire.${nocolor}"
-  HowToUse
-  exit 1
-fi
 
-if [[ -z $ARG_VALUE ]]; then
-  printf "${red}Le paramètre -v | --value est obligatoire.${nocolor}"
-  HowToUse
-  exit 1
+CheckMandatoryParams
+
+# Validate the syntax of the key and value
+validate_key_syntax "$ARG_KEY" "$ARG_VALUE"
+isValid=$?
+if [ $isValid -eq 1 ]; then
+	printf "${graydim}Cancel update.${nocolor}\n"
+	exit 0;
+	return
+elif [ $isValid -eq 2 ]; then
+	printf "${orange}Cannot validate syntax. ${graydim}Skip parameters validation.${nocolor}\n"
 fi
 
 update_sshd_config "$ARG_KEY" "$ARG_VALUE"
