init-iptables : create logic to add DROP ALL ssh rule before ACCEPT rules

diff --git a/scripts/init-iptables b/scripts/init-iptables
--- a/scripts/init-iptables
+++ b/scripts/init-iptables
@@ -51,7 +51,10 @@ commandName=`basename "$commandPath"`
 pwd=$(pwd)
 actualpwd=$(pwd)
 g_errors=()
+g_warnings=()
+g_notices=()
 cmd_iptables_found=false
+force_insert=false
 
 declare -a g_output=()
 declare -a ssh_rules_input_accept=()
@@ -68,7 +71,8 @@ declare -a ssh_allowed_ips=()
 ssh_denied_ips_str=
 declare -a ssh_denied_ips=()
 bastion=
-drop_ssh=true
+drop_ssh=false
+active_icmp=false
 
 
 CheckIptables() {
@@ -83,29 +87,78 @@ CheckIptables() {
 	fi
 }
 CheckIfParameters() {
-	if [ -z "$ssh_port" ] && [ -z "$ssh_allowed_ips_str" ] && [ -z "$ssh_denied_ips_str" ] && [ -z "$bastion" ]; then
+	# if [ -z "$ssh_port" ] || [ -z "$ssh_allowed_ips_str" ] && [ -z "$ssh_denied_ips_str" ] && [ -z "$bastion" ]; then
+	# 	return 1
+	# else
+	# 	return 0
+	# fi
+
+	if ([ ! -z "$ssh_allowed_ips_str" ] && [ ! -z "$ssh_denied_ips_str" ]) &&  [ -z "$ssh_port" ]; then
+		return 1
+	elif [ -z "$ssh_port" ] && [ -z "$ssh_allowed_ips_str" ] && [ -z "$ssh_denied_ips_str" ] && [ -z "$bastion" ] && [ "$active_icmp" = false ] && [ "$drop_ssh" = false ]; then
 		return 1
 	else
 		return 0
 	fi
+
 }
+
 CheckMandatoryParams() {
 	if [ $silent == false ]; then
 		printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
 	fi
 
-	# CHECK SSH
-	if [ $verbose == true ] && [ $silent == false ]; then
-		printf "${c__fctAction}Checking for SSH Port ...${nocolor}\n"
-	fi
-	
-	if [[ -z $ssh_port ]]; then
-		mand_errors+=("${c__error}parameter ${c__msgVar}-s | --sshport${c__error} is mandatory.${nocolor}")
-	else
-		if [ $verbose == true ]; then
-			printf "${c__fct2}SSH Port : ${c__value}${ssh_port}${nocolor}\n"
+	# if ssh_allowed_ips_str or ssh_denied_ips_str is not empty, check that ssh_port is not empty
+	if [ "$ssh_allowed_ips_str" != "" ] || [ "$ssh_denied_ips_str" != "" ]; then
+		if [ "$ssh_port" == "" ]; then
+			# printf "${c__error}parameter ${c__msgVar}-s | --ssh-port${c__error} is mandatory.${nocolor}\n"
+			mand_errors+=("${c__error}parameter ${c__msgVar}-p | --ssh-port${c__error} is mandatory.${nocolor}")
 		fi
 	fi
+
+	# if ssh_port is not empty, check that ssh_allowed_ips_str or ssh_denied_ips_str have at least one ip
+	if [ "$ssh_port" != "" ]; then
+		if [ "$ssh_allowed_ips_str" == "" ] && [ "$ssh_denied_ips_str" == "" ]; then
+			# printf "${c__error}parameter ${c__msgVar}-s | --allow-ip${c__error} or ${c__msgVar}-d | --deny-ip${c__error} is mandatory.${nocolor}\n"
+			mand_errors+=("${c__error}parameter ${c__msgVar}-s | --ssh-allow${c__error} or ${c__msgVar}-S | --ssh-deny${c__error} is mandatory.${nocolor}")
+		fi
+	fi
+
+	if [ "$ssh_allowed_ips_str" != "" ]; then
+		IFS=',' read -r -a tmp <<< "${ssh_allowed_ips_str}"
+		CheckIfIPsArrayOK "${tmp[@]}"
+		local test=$?
+		if [ $test -eq 1 ]; then
+			mand_errors+=("${c__error}parameter ${c__msgVar}-s | --ssh-allow${c__error} is not valid.${nocolor}")
+		fi
+	fi
+
+	if [ "$ssh_denied_ips_str" != "" ]; then
+		IFS=',' read -r -a tmp <<< "${ssh_denied_ips_str}"
+		CheckIfIPsArrayOK "${tmp[@]}"
+		local test=$?
+		if [ $test -eq 1 ]; then
+			mand_errors+=("${c__error}parameter ${c__msgVar}-S | --ssh-deny${c__error} is not valid.${nocolor}")
+		fi
+	fi
+
+	
+	
+
+
+
+	# CHECK SSH
+	# if [ $verbose == true ] && [ $silent == false ]; then
+	# 	printf "${c__fctAction}Checking for SSH Port ...${nocolor}\n"
+	# fi
+	
+	# if [[ -z $ssh_port ]]; then
+	# 	mand_errors+=("${c__error}parameter ${c__msgVar}-s | --ssh-port${c__error} is mandatory.${nocolor}")
+	# else
+	# 	if [ $verbose == true ]; then
+	# 		printf "${c__fct2}SSH Port : ${c__value}${ssh_port}${nocolor}\n"
+	# 	fi
+	# fi
 
 	# # CHECK ALLOW IP
 	# if [ $verbose == true ] && [ $silent == false ]; then
@@ -113,7 +166,7 @@ CheckMandatoryParams() {
 	# fi
 
 	# if [[ -z $ssh_allowed_ips_str ]]; then
-	# 	mand_errors+=("${c__error}parameter ${c__msgVar}-i | --allow-ip${c__error} is mandatory.${nocolor}")
+	# 	mand_errors+=("${c__error}parameter ${c__msgVar}-s | --allow-ip${c__error} is mandatory.${nocolor}")
 	# else
 	# 	if [ $verbose == true ]; then
 	# 		printf "${c__fct2}SSH allowed IPs : ${c__value}${ssh_allowed_ips_str[*]}${nocolor}\n"
@@ -126,7 +179,7 @@ CheckMandatoryParams() {
 	# fi
 
 	# if [[ -z $ssh_denied_ips_str ]]; then
-	# 	mand_errors+=("${c__error}parameter ${c__msgVar}-I | --deny-ip${c__error} is mandatory.${nocolor}")
+	# 	mand_errors+=("${c__error}parameter ${c__msgVar}-S | --deny-ip${c__error} is mandatory.${nocolor}")
 	# else
 	# 	if [ $verbose == true ]; then
 	# 		printf "${c__fct2}SSH denied IPs : ${c__value}${ssh_denied_ips_str[*]}${nocolor}\n"
@@ -167,7 +220,9 @@ CheckMandatoryParams() {
 check_valid_ip_cidr() {
 	local input="$1"
 
-	printf "${c__fct2}Checking ${c__value}${ip}${nocolor} validity ... ${nocolor}"
+	# if [ "$verbose" == true ]; then
+		printf "${c__fctAction}Checking ${c__value}${input}${nocolor} validity ... ${nocolor}"
+	# fi
 
 	# Validate IP with CIDR format
 	if [[ $input =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$ ]]; then
@@ -198,39 +253,33 @@ check_valid_ip_cidr() {
 	fi
 }
 
+CheckIfIPsArrayOK() {
+	local ips=("$@")
+	local isError=false
+	for ip in "${ips[@]}"; do		
 
-# ManageICMP(){
-# 	printf "${c__fctName}Adding ICMP rule ...${nocolor}\n"
-# 	# rules for ping
-# 	iptables > /dev/null
-# 	if [[ $? -eq 0 ]]; then
-# 		iptables -t filter -A INPUT -p icmp -j ACCEPT
-# 		iptables -t filter -A OUTPUT -p icmp -j ACCEPT
-# 	else
-# 		if [ "$verbose" == true]; then
-# 			printf "${c__error}iptables not found${nocolor}\n"
-# 		fi
-# 		g_errors+=("${c__error}ManageICMP - iptables not found${nocolor}")
-# 		exit 1
-# 	fi
-	
-# 	printf "\n${c__success}ICMP rules added${nocolor}
-# 	\n"
-# }
+		if [ -z "$ip" ]; then
+			g_errors+=("Allowed IP is empty")
+			continue
+		fi
 
+		check_valid_ip_cidr "$ip"
+		if [ $? -ne 0 ]; then
+			isError=true
+			break
+		fi
+	done
+
+	if [ $isError == true ]; then
+		return 1
+	else
+		return 0
+	fi
+}
 
 
 FindRule() {
 	local rule_str=$1
-
-	local ip=$2
-	local port=$3
-	local chain=$4 # INPUT or OUTPUT
-	local target=$5 # ACCEPT or DROP
-
-	if [ $verbose == true ]; then
-		printf "${c__fct2}Checking ${c__value2}${target} ${chain}${c__fct2} rule for IP ${c__value}${ip}${c__fct2} on port ${c__value}${port}${c__fct2}  ...${nocolor}"
-	fi	
 
 	# List iptables rules and search for the rule
 	local checkrule=$(iptables -S | grep -F "$rule_str")
@@ -256,17 +305,7 @@ FormatRules() {
 	local accept=()
 	local drop=()
 
-
-	# if [ -z "$drop_all" ]; then
-	# 	drop_all=false
-	# fi
-
 	printf "${c__fctName}${stringRule}${nocolor}\n"
-	# if [ $drop_all == true ]; then
-	# 	printf " - ${c__notice}Drop rule asked${nocolor}\n"
-	# else
-	# 	printf "\n"
-	# fi
 
 
 	# check if array is empty
@@ -306,43 +345,37 @@ FormatRules() {
 			continue
 		fi
 
-		printf "${c__fctAction}Formating rule for ${c__fct2}${ip}${nocolor}\n"
+		if [ $verbose == true ]; then
+			printf "${c__fctAction}Formating rule for ${c__fct2}${ip}${nocolor}\n"
+		fi
 
 		local rule="${chain} -s ${ip} -p tcp -m tcp --dport ${port} -j ${target}"
 
-		# check if rule already exists
-		FindRule "$rule" "$ip" "$port" "$chain" "$target"
-		if [ $? -ne 0 ]; then
-			printf " ${c__fctAction}Skip${nocolor}\n"
-			continue
+		if [ "$force_insert" = false ]; then
+			# check if rule already exists
+			# FindRule "$rule" "$ip" "$port" "$chain" "$target"
+			printf "${c__fct2}Checking ${c__value2}${target} ${chain}${c__fct2} rule for IP ${c__value}${ip}${c__fct2} on port ${c__value}${port}${c__fct2}  ...${nocolor}"
+			FindRule "$rule"
+			if [ $? -ne 0 ]; then
+				printf " ${c__fctAction}Skip${nocolor}\n"
+				g_notices+=("${c__warning}${ip}${c__notice} already has a ${c__warning}${target} ${chain}${c__notice} rule on port ${c__warning}${port}${nocolor}")
+				continue
+			else
+				printf "\n"
+			fi
 		else
-			printf "\n"
+			printf "${c__warning}Force insert rule ${c__notice}(because DROP RULE just added)${nocolor}\n"
 		fi
 
 		if [ "$verbose" == true ]; then
 			printf "${c__fctAction}Creating rule ${c__fct2}${rule}${nocolor}\n"
 		fi
 		accept+=("${rule}")
-
+		force_insert=false
 	done
 
-	
-	# # ! Add drop rule only if there is at least one accept rule
-	# if [ ${#accept[@]} -eq 0 ]; then
-	# 	printf "${c__warning}No accept rules to add${nocolor}\n"
-	# 	return 2
-	# else
-	# 	# insert drop rule for SSH to all ips
-	# 	if [ "$drop_all" = true ]; then
-	# 		drop+=("iptables -I INPUT -p tcp --dport $port -j DROP")
-	# 	fi
-	# fi
-
 	g_output=()
-	# # add drop rules first
-	# for line in "${drop[@]}"; do
-	# 	g_output+=("$line")
-	# done
+
 	# add accept rules
 	for line in "${accept[@]}"; do
 		g_output+=("$line")
@@ -451,6 +484,64 @@ InsertRules() {
 }
 
 
+ManageDropSSHRule() {
+	force_insert=false
+	# insert drop rule for SSH to all ips
+	
+	printf "🚨 ${c__fctName}Insert DROP ALL rule for SSH on port ${ssh_port}${nocolor}"
+	# ! Add drop rule only if there is at least one accept rule
+	# if [ "$drop_ssh" = true ]; then
+		
+		IFS=',' read -r -a allwd_ips <<< "${ssh_allowed_ips_str}"
+
+		if [ ${#allwd_ips[@]} -gt 0 ]; then
+			printf "\n"
+			CheckIfIPsArrayOK "${allwd_ips[@]}"
+			local test=$?
+			if [ $test -eq 0 ]; then
+				local drop=()
+				local droprule="INPUT -p tcp -m tcp --dport ${ssh_port} -j DROP"
+
+				printf "${c__fct2}Checking DROP rule ...${nocolor}"
+
+				FindRule "$droprule"
+				if [ $? -ne 0 ]; then
+					printf " ${c__fctAction}Skip${nocolor}\n"
+					g_notices+=("${c__notice}SSH DROP RULE allready exists${nocolor}")
+					return 3
+				else
+					printf " ${c__success}added${nocolor}\n"
+					drop+=("${droprule}")
+				fi
+
+				if [ ${#drop[@]} -gt 0 ]; then
+					printf "\n${c__fctName}Inserting SSH DROP rule${nocolor}\n"
+					InsertRules "${drop[@]}"
+					local test=$?
+					if [ $test -eq 0 ]; then
+						# printf "${c__success}SSH DROP rule added.${nocolor}\n"
+						force_insert=true
+						return 0
+					fi
+				else
+					printf "${c__fctAction}No SSH DROP rule to add${nocolor}\n"
+					return 2
+				fi
+			else
+				# printf " : ${c__error}Ips are invalid.${nocolor}\n"
+				return 1
+			fi
+		else
+			printf " : ${c__notice}Skip because of no ACCEPT rules${nocolor}\n"
+			g_notices+=("${c__notice}DROP rule not apply because of no ACCEPT rules")
+			return 2
+		fi
+	# else
+	# 	printf "${c__fct2} skipped.${nocolor}\n"
+	# 	return 2
+	# fi
+}
+
 
 ManageSSHDenyRules() {
 	FormatRules "Format SSH rules for denied ips" "$ssh_denied_ips_str" "$ssh_port" "INPUT" "DROP"
@@ -459,6 +550,7 @@ ManageSSHDenyRules() {
 		printf "${c__error}❌ Error while formatting denied SSH rules${nocolor}\n"
 		return 1
 	elif [ $result -eq 2 ]; then
+		# g_notices+=("${c__notice}No SSH rules to add for denied IPs${nocolor}")
 		return 2
 	else
 		# get values from g_output array
@@ -483,6 +575,7 @@ ManageSSHAllowRules() {
 		printf "${c__error}❌ Error while formatting allowed SSH rules${nocolor}\n"
 		return 1
 	elif [ $result -eq 2 ]; then
+		# g_notices+=("${c__notice}No SSH rules to add for allowed IPs${nocolor}")
 		return 2
 	else
 		# get values from g_output array
@@ -501,39 +594,75 @@ ManageSSHAllowRules() {
 }
 
 
+ManageICMPRules() {
+	local icmp_rule_input="INPUT -p icmp -j ACCEPT"
+	local icmp_rule_output="OUTPUT -p icmp -j ACCEPT"
+
+	printf "${c__fctName}Format ICMP rules${nocolor}\n"
+
+	InsertICMPRule "$icmp_rule_input" "INPUT"
+	local result=$?
+	if [ $result -eq 1 ]; then
+		# printf "${c__error}❌ Error while adding ICMP ${c__fct2}INPUT${c__error} rule${nocolor}\n"
+		g_errors+=("${c__error}Error while adding ICMP ${c__fct2}INPUT${c__error} rule${nocolor}")
+		return 1
+	elif [ $result -eq 2 ]; then
+		g_notices+=("${c__notice}ICMP ${c__fct2}INPUT${c__notice} rule : rule allready exists${nocolor}")
+		# return 2
+	fi
+
+	InsertICMPRule "$icmp_rule_output" "OUTPUT"
+	result=$?
+	if [ $result -eq 1 ]; then
+		# printf "${c__error}❌ Error while adding ICMP ${c__fct2}OUTPUT${c__error} rule${nocolor}\n"
+		g_errors+=("${c__error}Error while adding ICMP ${c__fct2}OUTPUT${c__error} rule${nocolor}")
+		return 1
+	elif [ $result -eq 2 ]; then
+		g_notices+=("${c__notice}ICMP ${c__fct2}OUPUT${c__notice} rule : rule allready exists${nocolor}")
+		# return 2
+	fi
+}
+
+InsertICMPRule() {
+	local rule="$1"
+	local target="$2"
+
+	printf "${c__fct2}Checking ICMP ${target} rule ...${nocolor}"
+	FindRule "$rule"
+	if [ $? -ne 0 ]; then
+		printf " ${c__fctAction}Skip${nocolor}\n"
+		return 2
+	else
+		printf "\n"
+	fi
+
+
+	if [ $silent == false ]; then
+		printf "${c__fct2}Execute rule ${c__value}${rule}${nocolor} ... "
+	fi
+
+	iptables -I $rule > /dev/null 2>&1
+	local test=$?
+	if [ $test -eq 0 ]; then
+		if [ $silent == false ]; then
+			printf "${c__success}Done.${nocolor}\n"
+		fi
+	else
+		if [ $silent == false ]; then
+			printf "${c__error}Error.${nocolor}\n"
+		fi
+		g_errors+=("${c__error}Error while adding rule ${c__fct2}${rule}${nocolor}")
+		return 1
+	fi
+}
+
+ManageBastionRules() {
+	printf "${c__fctName}Format bastion rules${nocolor}\n"
+
+}
 
 
 
-
-# ApplyRules() {
-# 	local rules_input_drop=$1
-# 	local rules_input_accept=$2
-# 	# insert drop rule for SSH to all ips
-# 	if [ ${#rules_input_drop[@]} -gt 0 ]; then
-# 		printf "${c__fctAction}Start inserting ${c__value2}${#rules_input_drop[@]}${c__fctAction} for INPUT DROP${nocolor}\n"
-# 		InsertRules "${rules_input_drop[@]}"
-# 	else
-# 		if [ $silent == false ]; then
-# 			printf "${c__fctAction}No INPUT DROP rules${nocolor}\n"
-# 		fi
-# 	fi
-
-# 	# insert accept rules for SSH to all ips
-# 	if [ ${#rules_input_accept[@]} -gt 0 ]; then
-# 		printf "${c__fctAction}Start inserting ${c__value2}${#rules_input_accept[@]}${c__fctAction} for INPUT ACCEPT${nocolor}\n"
-# 		InsertRules "${rules_input_accept[@]}"
-# 	else
-# 		if [ $silent == false ]; then
-# 			printf "${c__fctAction}No INPUT ACCEPT rules${nocolor}\n"
-# 		fi
-# 	fi
-# }
-
-# ManageResponse(){
-# 	# si une machine établie une connexion, on laisser passer la communication
-# 	# iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-# 	# iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-# }
 
 
 StartText () {
@@ -547,13 +676,17 @@ HowToUse() {
 	printf "   DROP rules are inserts BEFORE ACCEPT rules.${nocolor}\n"
 
 	printf "\n"
-	printf "${commandName} -p 2222 -b 192.168.0.10 -s "192.168.0.1/24,172.0.0.1/24" -S "10.10.10.1/24,10.10.200" --verbose --slient${nocolor}\n"
+	printf "${commandName} -p 2222 -b 192.168.0.10 -s "192.168.0.1/24,172.0.0.1/24" -S "10.10.10.1/24,10.10.72.0/16" --icmp --drop-ssh --verbose --slient${nocolor}\n"
 	printf "\n"
 	printf "${whiitebold}Parameters :${gray}\n"
-	printf "    -p  --sshport   : SSH port\n"
+	printf "    -p  --ssh-port   : SSH port\n"
 	printf "    -b  --bastion   : Access point to connect to this machine\n"
+	printf "\n"
 	printf "    -s  --ssh-allow : Array of allowed ips to connect throught SSH (CIDR must be present)\n"
 	printf "    -S  --ssh-deny  : Array of denied ips to connect throught SSH (CIDR must be present)\n"
+	printf "\n"
+	printf "    --icmp          : Flag to add ICMP rules\n"
+	printf "    --drop-ssh      : Flag to drop all ssh connections\n"
 	printf "\n"
 	printf "  --verbose         : show logs\n"
 	printf "  --silent          : hide logs\n"
@@ -578,6 +711,22 @@ EndOfScript() {
 		# fi
 	fi
 
+	# show warning messages if there are
+	if [[ ${#g_warnings[@]} -gt 0 ]]; then
+		printf "${c__warning}⚠️ ${#g_warnings[@]} warning(s)${nocolor}\n"
+		for warn in "${g_warnings[@]}"; do
+			printf "  ${c__warning}- ${warn}${nocolor}\n"
+		done
+	fi
+
+	# show notice messages if there are
+	if [[ ${#g_notices[@]} -gt 0 ]]; then
+		printf "${c__notice}📢 ${#g_notices[@]} notice(s)${nocolor}\n"
+		for notice in "${g_notices[@]}"; do
+			printf "  ${c__notice}- ${notice}${nocolor}\n"
+		done
+	fi
+
 	if [[ $silent == false ]]; then
 		printf "👋 ${blue}Bye bye${nocolor} 👋\n"
 	fi
@@ -594,7 +743,7 @@ EndOfScript() {
 # Récupération des paramètres en utilisant getopts
 while [[ $# -gt 0 ]]; do
   case $1 in
-    -p | --sshport)
+    -p | --ssh-port)
       shift
       ssh_port=$1
       ;;
@@ -609,6 +758,10 @@ while [[ $# -gt 0 ]]; do
 	-b | --bastion)
 	  shift
 	  bastion=$1
+	  ;;
+	--icmp)
+	  shift
+	  active_icmp=true
 	  ;;
 	--drop-ssh)
 	  shift
@@ -641,15 +794,14 @@ if [ $? -eq 1 ]; then
 	exit 1
 fi
 
-# CheckIptables
-# if [ $? -eq 1 ]; then
-# 	exit 1
-# fi
+CheckIptables
+if [ $? -eq 1 ]; then
+	exit 1
+fi
 
 if [[ "$silent" == false ]]; then
 	StartText
 fi
-
 
 CheckMandatoryParams
 if [ $? -eq 1 ]; then
@@ -657,9 +809,36 @@ if [ $? -eq 1 ]; then
 fi
 
 
-ManageSSHDenyRules
-printf "\n"
-ManageSSHAllowRules
+if [ "$drop_ssh" = true ]; then
+	ManageDropSSHRule
+	test=$?
+	if [ $test -eq 1 ]; then
+		EndOfScript
+		exit 1
+	fi
+fi
+
+
+
+
+# ManageBastionRules
+
+if [ ! -z "$ssh_denied_ips_str" ]; then
+	# printf "\n"
+	ManageSSHDenyRules
+fi
+
+if [ ! -z "$ssh_allowed_ips_str" ]; then
+	# printf "\n"
+	ManageSSHAllowRules
+fi
+
+
+if [ $active_icmp == true ]; then
+	# printf "\n"
+	ManageICMPRules
+fi
+
 
 
 EndOfScript
