init-ssh : check if user or group exists in linux system

diff --git a/scripts/init-ssh b/scripts/init-ssh
--- a/scripts/init-ssh
+++ b/scripts/init-ssh
@@ -65,7 +65,8 @@ existing_denied_groups=()
 ## EDITABLES (does match with system file)
 # sshd_config="../files/etc/ssh/sshd_config"
 # hosts_allow="../files/etc/hosts.allow"
-sshd_config="/etc/ssh/sshd_config"
+sshd_config=
+# sshd_config="/etc/ssh/sshd_config"
 hosts_allow="/etc/hosts.allow"
 
 PWD=$(pwd)
@@ -100,41 +101,59 @@ CheckMandatoryParams() {
 		printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
 	fi
 	
-	# Vérification des paramètres obligatoires
+	# check file parameter
 	if [ $verbose == true ] && [ $silent == false ]; then
-		printf "${c__fctAction}Checking for ssh parameter ...${nocolor}\n"
+		printf "${c__fctAction}Checking for file parameter ...${nocolor}\n"
 	fi
 
-	if [[ -z $ssh_port ]]; then
-		printf "${c__error}parameter ${c__msgVar}-p | --ssh-port${c__error} is mandatory.${nocolor}\n"
-		errors+=("SSH port is mandatory")
+	if [[ -z $sshd_config ]]; then
+		printf "${c__error}parameter ${c__msgVar}-f | --file${c__error} is mandatory.${nocolor}\n"
+		errors+=("file is mandatory")
 		isError=true
 	else
 		if [ $verbose == true ] && [ $silent == false ]; then
-			printf "    ${c__fct2}SSH Port : ${c__value}${ssh_port}${nocolor}\n"
+			printf "    ${c__fct2}file : ${c__value}${sshd_config}${nocolor}\n"
 		fi
 	fi
 
-	if [ $verbose == true ] && [ $silent == false ]; then
-		printf "${c__fctAction}Checking for network host parameter ...${nocolor}\n"
-	fi
+	# # check ssh port parameter
+	# if [ $verbose == true ] && [ $silent == false ]; then
+	# 	printf "${c__fctAction}Checking for ssh parameter ...${nocolor}\n"
+	# fi
 
-	if [[ -z $network_cidr ]]; then
-		printf "${c__error}parameter ${c__msgVar}-n | --network-host${c__error} is mandatory.${nocolor}
-		\n"
-		errors+=("Network IP/CIDR is mandatory")
-		exit 1
-	else
-		if [ $verbose == true ] && [ $silent == false ]; then
-			printf "    ${c__fct2}network host : ${c__value}${network_cidr}${nocolor}\n"
-		fi
-	fi
+	# if [[ -z $ssh_port ]]; then
+	# 	printf "${c__error}parameter ${c__msgVar}-p | --ssh-port${c__error} is mandatory.${nocolor}\n"
+	# 	errors+=("SSH port is mandatory")
+	# 	isError=true
+	# else
+	# 	if [ $verbose == true ] && [ $silent == false ]; then
+	# 		printf "    ${c__fct2}SSH Port : ${c__value}${ssh_port}${nocolor}\n"
+	# 	fi
+	# fi
+
+
+	# # check network host parameter
+	# if [ $verbose == true ] && [ $silent == false ]; then
+	# 	printf "${c__fctAction}Checking for network host parameter ...${nocolor}\n"
+	# fi
+
+	# if [[ -z $network_cidr ]]; then
+	# 	printf "${c__error}parameter ${c__msgVar}-n | --network-host${c__error} is mandatory.${nocolor}
+	# 	\n"
+	# 	errors+=("Network IP/CIDR is mandatory")
+	# 	isError=true
+	# else
+	# 	if [ $verbose == true ] && [ $silent == false ]; then
+	# 		printf "    ${c__fct2}network host : ${c__value}${network_cidr}${nocolor}\n"
+	# 	fi
+	# fi
+
 
 	if [ $isError == true ]; then
 		exit 1
 	else
 		if [ $verbose == true ] && [ $silent == false ]; then
-			printf "\n  ${c__success}Mandatory parameters OK${nocolor}\n"
+			printf "  ${c__success}Mandatory parameters OK${nocolor}\n"
 		fi
 	fi
 }
@@ -145,43 +164,72 @@ CheckMandatoryParams() {
 
 CheckIfItemExists() {
 	local item=$1
+	local type=$2
 
-	if ! command -v getent > /dev/null; then
-		gentenvInvalid=true
-		if [ $verbose == true ]; then
-			printf "${c__error}command getenv not found${nocolor}\n"
-		fi
-		return 2
-	else
-		if [ $verbose == true ]; then
-			printf "${c__fctAction}command getenv found${nocolor}\n"
-		fi
-		gentenvInvalid=false
-	fi
+	# TODO: check if string is a user or a group
 
-	printf "   ${c__msgVar}${item}${c__fctAction} ...${nocolor}"
-	getent passwd $item > /dev/null 2>&1
-	local result=$?
-	if [ $result -eq 0 ]; then
-		printf "${c__success} found${nocolor}\n"
-		return 0
+	if [ "$type" == 'user' ]; then
+		printf "${c__fctAction}Checking if ${c__value}$item${c__fctAction} is a valid Linux user ...${nocolor}\n"
+		if id -u "$item" >/dev/null 2>&1; then
+			printf "${c__value}$item${c__fctAction} is a valid Linux user.${nocolor}\n"
+			return 0
+		else
+			printf "${c__value}$item${c__error} is not a valid Linux user.${nocolor}\n"
+			return 1
+		fi
+	elif [ "$type" == 'group' ]; then
+		printf "${c__fctAction}Checking if ${c__value}$item${c__fctAction} is a valid Linux group ...${nocolor}\n"
+		if ! command -v getent > /dev/null; then
+			gentenvInvalid=true
+			if [ $verbose == true ]; then
+				printf "${c__error}command getenv not found${nocolor}\n"
+			fi
+			return 2
+		else
+			if [ $verbose == true ]; then
+				printf "${c__fctAction}command getenv found${nocolor}\n"
+			fi
+			gentenvInvalid=false
+
+			# Check if the string is a valid group
+			if getent group "$item" > /dev/null 2>&1; then
+				printf "${c__value}$item${c__fctAction} is a valid Linux group.${nocolor}\n"
+				return 0
+			else
+				printf "${c__value}$item${c__error} is not a valid Linux group.${nocolor}\n"
+				return 1
+			fi
+		fi
 	else
-		printf "${c__warning} not found${nocolor}\n"
+		printf "${c__error}parameter ${c__msgVar}type${c__error} is mandatory.${nocolor}\n"
+		errors+=("type is mandatory")
 		return 1
 	fi
+
+	# printf "   ${c__msgVar}${item}${c__fctAction} ...${nocolor}"
+	# getent passwd $item > /dev/null 2>&1
+	# local result=$?
+	# if [ $result -eq 0 ]; then
+	# 	printf "${c__success} found${nocolor}\n"
+	# 	return 0
+	# else
+	# 	printf "${c__error} does not exists${nocolor}.\n"
+	# 	printf "${c__notice}Create user before use this script${nocolor}\n"
+	# 	return 1
+	# fi
 }
 
 
 CheckAllowUsers() {
 	for usr in "${allowed_users[@]}"; do
 		if [ $gentenvInvalid == false ]; then
-			CheckIfItemExists $usr
+			CheckIfItemExists $usr 'user'
 			local test=$?
 			if [ $test -eq 0 ]; then
 				existing_allowed_users+=("$usr")
 			elif [ $test -eq 2 ]; then
 				if [ $silent == false ]; then
-					printf "${c__warning}check for \"${usr}\" fail${nocolor}\n"
+					printf "${c__error}check for \"${usr}\" fail${nocolor}\n"
 				fi
 			fi
 		else
@@ -215,13 +263,13 @@ ManageAllowUsers() {
 CheckAllowGroups() {
 	for grp in "${allowed_groups[@]}"; do
 		if [ $gentenvInvalid == false ]; then
-			CheckIfItemExists $grp
+			CheckIfItemExists $grp 'group'
 			local test=$?
 			if [ $test -eq 0 ]; then
 				existing_allowed_groups+=("$grp")
 			elif [ $test -eq 2 ]; then
 				if [ $silent == false ]; then
-					printf "${c__warning}check for \"${grp}\" fail${nocolor}\n"
+					printf "${c__error}check for \"${grp}\" fail${nocolor}\n"
 				fi
 			fi
 		else
@@ -237,7 +285,13 @@ ManageAllowGroups() {
 			printf "${c__fctName}Manage allowed groups ...${nocolor}\n"
 		fi
 
-		bash ./update-config -k AllowGroups -v $(join_by , "${existing_allowed_groups[@]}")
+		if [ $silent == true ]; then
+			bash ./update-config -k AllowGroups -v $(join_by , "${existing_allowed_groups[@]}") -f "$sshd_config" --silent
+		elif [ $verbose == true ]; then
+			bash ./update-config -k AllowGroups -v $(join_by , "${existing_allowed_groups[@]}") -f "$sshd_config" --verbose
+		else
+			bash ./update-config -k AllowGroups -v $(join_by , "${existing_allowed_groups[@]}") -f "$sshd_config"
+		fi
 	else
 		if [ $silent == false ]; then
 			printf "${c__fctAction}No existing allowed groups to manage${nocolor}\n"
@@ -249,13 +303,13 @@ ManageAllowGroups() {
 CheckDeniedUsers() {
 	for usr in "${denied_users[@]}"; do
 		if [ $gentenvInvalid == false ]; then
-			CheckIfItemExists $usr
+			CheckIfItemExists $usr 'user'
 			local test=$?
 			if [ $test -eq 0 ]; then
 				existing_denied_users+=("$usr")
 			elif [ $test -eq 2 ]; then
 				if [ $silent == false ]; then
-					printf "${c__warning}check for \"${usr}\" fail${nocolor}\n"
+					printf "${c__error}check for \"${usr}\" fail${nocolor}\n"
 				fi
 			fi
 		else
@@ -270,8 +324,14 @@ ManageDeniedUsers() {
 		if [ $silent == false ]; then
 			printf "${c__fctName}Manage denied users ...${nocolor}\n"
 		fi
-		
-		bash ./update-config -k DenyUsers -v $(join_by , "${existing_denied_users[@]}")
+
+		if [ $silent == true ]; then
+			bash ./update-config -k DenyUsers -v $(join_by , "${existing_denied_users[@]}") -f "$sshd_config" --silent
+		elif [ $verbose == true ]; then
+			bash ./update-config -k DenyUsers -v $(join_by , "${existing_denied_users[@]}") -f "$sshd_config" --verbose
+		else
+			bash ./update-config -k DenyUsers -v $(join_by , "${existing_denied_users[@]}") -f "$sshd_config"
+		fi
 	else
 		if [ $silent == false ]; then
 			printf "${c__fctAction}No existing denied users to manage${nocolor}\n"
@@ -283,13 +343,13 @@ ManageDeniedUsers() {
 CheckDeniedGroups() {
 	for grp in "${denied_groups[@]}"; do
 		if [ $gentenvInvalid == false ]; then
-			CheckIfItemExists $grp
+			CheckIfItemExists $grp 'group'
 			local test=$?
 			if [ $test -eq 0 ]; then
 				existing_denied_groups+=("$grp")
 			elif [ $test -eq 2 ]; then
 				if [ $silent == false ]; then
-					printf "${c__warning}check for \"${grp}\" fail${nocolor}\n"
+					printf "${c__error}check for \"${grp}\" fail${nocolor}\n"
 				fi
 			fi
 		else
@@ -305,7 +365,13 @@ ManageDeniedGroups() {
 			printf "${c__fctName}Manage denied groups ...${nocolor}\n"
 		fi
 
-		bash ./update-config -k DenyGroups -v $(join_by , "${existing_denied_groups[@]}")
+		if [ $silent == true ]; then
+			bash ./update-config -k DenyGroups -v $(join_by , "${existing_denied_groups[@]}") -f "$sshd_config" --silent
+		elif [ $verbose == true ]; then
+			bash ./update-config -k DenyGroups -v $(join_by , "${existing_denied_groups[@]}") -f "$sshd_config" --verbose
+		else
+			bash ./update-config -k DenyGroups -v $(join_by , "${existing_denied_groups[@]}") -f "$sshd_config"
+		fi
 	else
 		if [ $silent == false ]; then
 			printf "${c__fctAction}No existing denied groups to manage${nocolor}\n"
@@ -427,9 +493,11 @@ HowToUse() {
 	printf "  - It will update network configuration\n"
 	printf "  - It will allow users and groups to connect${nocolor}\n"
 	printf "\n"
-	printf "${commandName} -p 2222 -n 192.168.0.1/24 -u username1,sshuser@ip:port -g group1,group2 -U username3,sshuser@ip:port -G group4${nocolor}"
+	printf "${commandName} -p 2222 -n 192.168.0.1/24 -u username1,sshuser@ip:port -g group1,group2 -U username3,sshuser@ip:port -G group4${nocolor}\n"
 	printf "\n"
 	printf "${whiitebold}Parameters :${gray}\n"
+	printf "  -f  --file         : SSH config file (/etc/ssh/sshd_config)\n"
+	printf "\n"
 	printf "  -p  --ssh-port     : SSH port\n"
 	printf "  -n  --network-host : Network host\n"
 	printf "\n"
@@ -479,6 +547,10 @@ while [[ $# -gt 0 ]]; do
       	shift
       	denied_groups=($(echo "$1" | tr ',' ' '))
       	;;
+	-f | --file)
+		shift
+		sshd_config=$1
+		;;
 	--verbose)
 		shift
 		verbose=true
@@ -511,7 +583,7 @@ if [[ $silent == false ]]; then
 	StartText
 fi
 
-# CheckMandatoryParams
+CheckMandatoryParams
 
 
 ManageSSH
