init-users DONE.

diff --git a/scripts/init-ssh b/scripts/init-ssh
--- a/scripts/init-ssh
+++ b/scripts/init-ssh
@@ -27,6 +27,8 @@ c__fct2=$gray
 c__msgVar=$graybold
 c__value=$blue
 c__error=$red
+c__warning=$orange
+c__notice=$yellow
 c__success=$green
 
 
@@ -35,9 +37,6 @@ c__success=$green
 ###############
 commandPath=$0
 commandName=`basename "$commandPath"`
-pwd=$(pwd)
-actualpwd=$(pwd)
-silent=false
 
 ssh_port=
 network_cidr=
@@ -60,6 +59,12 @@ existing_denied_groups=()
 sshd_config="../files/etc/ssh/sshd_config"
 PWD=$(pwd)
 errors=()
+pwd=$(pwd)
+actualpwd=$(pwd)
+gentenvInvalid=false
+
+verbose=false
+silent=false
 
 function join_by {
   local d=${1-} f=${2-}
@@ -77,28 +82,50 @@ CheckIfRoot() {
 }
 
 CheckMandatoryParams() {
-	printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
+	local isError=false
+	if [ $verbose == true ] && [ $silent == false ]; then
+		printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
+	fi
+	
 	# Vérification des paramètres obligatoires
-	printf "${c__fctAction}Checking for ssh parameter ...${nocolor}\n"
-	if [[ -z $ssh_port ]]; then
-		printf "${c__error}parameter ${c__msgVar}-s | --ssh-port${c__error} is mandatory.${nocolor}\n"
-		errors+=("SSH port is mandatory")
-		exit 1
-	else
-		printf "${c__fct2}SSH Port : ${c__value}${ssh_port}${nocolor}\n"
+	if [ $verbose == true ] && [ $silent == false ]; then
+		printf "${c__fctAction}Checking for ssh parameter ...${nocolor}\n"
 	fi
 
-	printf "${c__fctAction}Checking for network IP/CIDIR parameter ...${nocolor}\n"
+	if [[ -z $ssh_port ]]; then
+		printf "${c__error}parameter ${c__msgVar}-p | --ssh-port${c__error} is mandatory.${nocolor}\n"
+		errors+=("SSH port is mandatory")
+		isError=true
+	else
+		if [ $verbose == true ] && [ $silent == false ]; then
+			printf "    ${c__fct2}SSH Port : ${c__value}${ssh_port}${nocolor}\n"
+		fi
+	fi
+
+	if [ $verbose == true ] && [ $silent == false ]; then
+		printf "${c__fctAction}Checking for network host parameter ...${nocolor}\n"
+	fi
+
 	if [[ -z $network_cidr ]]; then
-		printf "${c__error}parameter ${c__msgVar}-n | --network-cidr${c__error} is mandatory.${nocolor}
+		printf "${c__error}parameter ${c__msgVar}-n | --network-host${c__error} is mandatory.${nocolor}
 		\n"
 		errors+=("Network IP/CIDR is mandatory")
 		exit 1
 	else
-		printf "${c__fct2}network IP/CIDIR : ${c__value}${network_cidr}${nocolor}\n"
+		if [ $verbose == true ] && [ $silent == false ]; then
+			printf "    ${c__fct2}network host : ${c__value}${network_cidr}${nocolor}\n"
+		fi
 	fi
-	printf "\n${c__success}Mandatory parameters OK${nocolor}
-	\n"
+
+	if [ $isError == true ]; then
+		exit 1
+	else
+		if [ $verbose == true ] && [ $silent == false ]; then
+printf "
+  ${c__success}Mandatory parameters OK${nocolor}
+"
+		fi
+	fi
 }
 
 ##########
@@ -106,107 +133,243 @@ CheckMandatoryParams() {
 ##########
 CheckIfUserExists() {
 	local user=$1
-	printf "${c__fctName}Checking user $user ...${nocolor}\n"
+	if [ $silent == false ]; then
+		printf "${c__fctName}Checking user $user ...${nocolor}\n"
+	fi
+
+	if ! command -v getent > /dev/null; then
+		gentenvInvalid=true
+		printf "${c__error}command getenv not found${nocolor}\n"
+		return 2
+	else
+		gentenvInvalid=false
+	fi
+
 	getent passwd $user > /dev/null
 	if [ $? -eq 0 ]; then
-		printf "${c__success}user ${whiitebold}$user${c__success} exist${nocolor}
-		\n"
+		if [ $silent == false ]; then
+			printf "${c__success}user ${whiitebold}$user${c__success} exist${nocolor}\n"
+		fi
 		return 0
 	else
-		printf "${c__error}user ${whiitebold}$user${c__error} not exist${nocolor}
-		\n"
+		if [ $silent == false ]; then
+			printf "${c__error}user ${whiitebold}$user${c__error} not exist${nocolor}\n"
+		fi
 		return 1
 	fi
 }
 CheckIfGroupExists() {
 	local group=$1
-	printf "${c__fctName}Checking group $group ...${nocolor}\n"
+	if [ $silent == false ]; then
+		printf "${c__fctName}Checking group $group ...${nocolor}\n"
+	fi
+
+	if ! command -v getent > /dev/null; then
+		gentenvInvalid=true
+		printf "${c__error}command getenv not found${nocolor}\n"
+		return 2
+	else
+		gentenvInvalid=false
+	fi
+	
 	getent group $group > /dev/null
 	if [ $? -eq 0 ]; then
-		printf "${c__success}group ${whiitebold}$group${c__success} exist${nocolor}
-		\n"
+		
+		if [ $silent == false ]; then
+			printf "${c__success}group ${whiitebold}$group${c__success} exist${nocolor}\n"
+		fi
 		return 0
 	else
-		printf "${c__error}group ${whiitebold}$group${c__error} not exist${nocolor}
-		\n"
+		if [ $silent == false ]; then
+			printf "${c__error}group ${whiitebold}$group${c__error} not exist${nocolor}\n"
+		fi
 		return 1
 	fi
 }
 
+
 CheckAllowUsers() {
 	for usr in "${allowed_users[@]}"; do
-		CheckIfUserExists $usr
-		if [ $? -eq 0 ]; then
-			existing_allowed_users+=("$usr")
+		if [ $gentenvInvalid == false ]; then
+			CheckIfUserExists $usr
+			local test=$?
+			if [ $test -eq 0 ]; then
+				existing_allowed_users+=("$usr")
+			elif [ $test -eq 2 ]; then
+				if [ $silent == false ]; then
+					printf "${c__warning}check for \"${usr}\" fail${nocolor}\n"
+				fi
+			fi
+		else
+			if [ $silent == false ]; then
+				printf "${c__notice}check skip for ${whiitebold}\"${usr}\"${nocolor}\n"
+			fi
 		fi
 	done
 }
 ManageAllowUsers() {
-	printf "${c__fctName}Manage allowed users ...${nocolor}\n"
-	# Configuration des utilisateurs autorisés
 	if [[ ${#existing_allowed_users[@]} -gt 0 ]]; then
+		if [ $silent == false ]; then
+			printf "${c__fctName}Manage allowed users ...${nocolor}\n"
+		fi
+		
 		bash ./update-ssh-config -k AllowUsers -v $(join_by , "${existing_allowed_users[@]}")
 	else
-		printf "${c__fctAction}No existing allowed users to add${nocolor}\n"
+		if [ $silent == false ]; then
+			printf "${c__fctAction}No existing allowed users to manage${nocolor}\n"
+		fi
 	fi
 	printf "\n"
 }
 
 CheckAllowGroups() {
 	for grp in "${allowed_groups[@]}"; do
-		CheckIfGroupExists $grp
-		if [ $? -eq 0 ]; then
-			existing_allowed_groups+=("$grp")
+		if [ $gentenvInvalid == false ]; then
+			CheckIfGroupExists $grp
+			local test=$?
+			if [ $test -eq 0 ]; then
+				existing_allowed_groups+=("$grp")
+			elif [ $test -eq 2 ]; then
+				if [ $silent == false ]; then
+					printf "${c__warning}check for \"${grp}\" fail${nocolor}\n"
+				fi
+			fi
+		else
+			if [ $silent == false ]; then
+				printf "${c__notice}check skip for ${whiitebold}\"${grp}\"${nocolor}\n"
+			fi
 		fi
 	done
 }
 ManageAllowGroups() {
-	printf "${c__fctName}Manage allowed groups ...${nocolor}\n"
-	# Configuration des utilisateurs autorisés
 	if [[ ${#existing_allowed_groups[@]} -gt 0 ]]; then
+		if [ $silent == false ]; then
+			printf "${c__fctName}Manage allowed groups ...${nocolor}\n"
+		fi
+
 		bash ./update-ssh-config -k AllowGroups -v $(join_by , "${existing_allowed_groups[@]}")
 	else
-		printf "${c__fctAction}No allowed groups to add${nocolor}\n"
+		if [ $silent == false ]; then
+			printf "${c__fctAction}No existing allowed groups to manage${nocolor}\n"
+		fi
 	fi
 	printf "\n"
 }
 
 CheckDeniedUsers() {
 	for usr in "${denied_users[@]}"; do
-		CheckIfUserExists $usr
-		if [ $? -eq 0 ]; then
-			existing_denied_users+=("$usr")
+		if [ $gentenvInvalid == false ]; then
+			CheckIfUserExists $usr
+			local test=$?
+			if [ $test -eq 0 ]; then
+				existing_denied_users+=("$usr")
+			elif [ $test -eq 2 ]; then
+				if [ $silent == false ]; then
+					printf "${c__warning}check for \"${usr}\" fail${nocolor}\n"
+				fi
+			fi
+		else
+			if [ $silent == false ]; then
+				printf "${c__notice}check skip for ${whiitebold}\"${usr}\"${nocolor}\n"
+			fi
 		fi
 	done
 }
 ManageDeniedUsers() {
-	printf "${c__fctName}Manage denied users ...${nocolor}\n"
-	# Configuration des utilisateurs autorisés
 	if [[ ${#existing_denied_users[@]} -gt 0 ]]; then
+		if [ $silent == false ]; then
+			printf "${c__fctName}Manage denied users ...${nocolor}\n"
+		fi
+		
 		bash ./update-ssh-config -k DenyUsers -v $(join_by , "${existing_denied_users[@]}")
 	else
-		printf "${c__fctAction}No denied users to add${nocolor}\n"
+		if [ $silent == false ]; then
+			printf "${c__fctAction}No existing denied users to manage${nocolor}\n"
+		fi
 	fi
 	printf "\n"
 }
 
 CheckDeniedGroups() {
 	for grp in "${denied_groups[@]}"; do
-		CheckIfGroupExists $grp
-		if [ $? -eq 0 ]; then
-			existing_denied_groups+=("$grp")
+		if [ $gentenvInvalid == false ]; then
+			CheckIfGroupExists $grp
+			local test=$?
+			if [ $test -eq 0 ]; then
+				existing_denied_groups+=("$grp")
+			elif [ $test -eq 2 ]; then
+				if [ $silent == false ]; then
+					printf "${c__warning}check for \"${grp}\" fail${nocolor}\n"
+				fi
+			fi
+		else
+			if [ $silent == false ]; then
+				printf "${c__notice}check skip for ${whiitebold}\"${grp}\"${nocolor}\n"
+			fi
 		fi
 	done
 }
 ManageDeniedGroups() {
-	printf "${c__fctName}Manage denied groups ...${nocolor}\n"
-	# Configuration des utilisateurs autorisés
 	if [[ ${#existing_denied_groups[@]} -gt 0 ]]; then
+		if [ $silent == false ]; then
+			printf "${c__fctName}Manage denied groups ...${nocolor}\n"
+		fi
+
 		bash ./update-ssh-config -k DenyGroups -v $(join_by , "${existing_denied_groups[@]}")
 	else
-		printf "${c__fctAction}No denied groups to add${nocolor}\n"
+		if [ $silent == false ]; then
+			printf "${c__fctAction}No existing denied groups to manage${nocolor}\n"
+		fi
 	fi
 	printf "\n"
+}
+
+########
+## SSH
+########
+ManageSSH() {
+	if [ $silent == false ]; then
+		printf "${c__fctName}Update ssh port ...${nocolor}\n"
+	fi
+
+	if [ $silent == true ] && [ $verbose == true ]; then
+		bash ./update-ssh-config -k Port -v $ssh_port --verbose --silent
+	elif [ $silent == true ]; then
+		bash ./update-ssh-config -k Port -v $ssh_port --silent
+	elif [ $verbose == true ]; then
+		bash ./update-ssh-config -k Port -v $ssh_port --verbose
+	else
+		bash ./update-ssh-config -k Port -v $ssh_port
+	fi
+}
+
+########
+## NETWORK
+########
+ManageNetwork() {
+	if [ $silent == false ]; then
+		printf "${c__fctName}Manage network ...${nocolor}\n"
+	fi
+
+	if [ -f "/etc/hosts.allow" ]; then
+		echo "sshd: 10.10.200.0/24 : ALLOW" >> "/etc/hosts.allow"
+		if [ $silent == false ]; then
+			printf "${c__success}file \"/etc/hosts.allow\" updated${nocolor}\n"
+		fi
+	else
+		if [ $silent == false ]; then
+			printf "${c__error}file \"/etc/hosts.allow\" does not exists. ${graydim}Skip${nocolor}\n"
+		fi
+	fi
+	# if [ $silent == true ] && [ $verbose == true ]; then
+	# 	bash ./update-ssh-config -k Port -v $ssh_port --verbose --silent
+	# elif [ $silent == true ]; then
+	# 	bash ./update-ssh-config -k Port -v $ssh_port --silent
+	# elif [ $verbose == true ]; then
+	# 	bash ./update-ssh-config -k Port -v $ssh_port --verbose
+	# else
+	# 	bash ./update-ssh-config -k Port -v $ssh_port
+	# fi
 }
 
 
@@ -214,22 +377,16 @@ ManageDeniedGroups() {
 ## CONFIG
 ###########
 SavePreviousFile() {
-	# Sauvegarde du fichier de configuration original
+	if [ $silent == false ]; then
+		printf "${c__fctAction}Save previous config file ...${nocolor}\n"
+	fi
 	cp $sshd_config $sshd_config.backup
 }
 
-UpdateConfig() {
-	printf "${gray}Start reconfiguring ...${nocolor}\n"
-	# lancement de la re-config
-	# sudo ./scripts/update-ssh-config -k Port -v $ssh_port
-	# sudo ./scripts/update-ssh-config -k ListenAddress -v $network_cidr
-	# sudo ./scripts/update-ssh-config -k AllowUsers -v $allowed_users
-	# sudo ./scripts/update-ssh-config -k AllowGroups -v $allowed_groups
-	# sudo ./scripts/update-ssh-config -k DenyUsers -v $denied_users
-	# sudo ./scripts/update-ssh-config -k DenyGroups -v $denied_groups
-}
-
 DisplayConfig() {
+	if [ $silent == false ]; then
+		printf "${c__fctAction}Display config file ...${nocolor}\n"
+	fi
 	cat "$sshd_config"
 }
 
@@ -237,11 +394,11 @@ DisplayConfig() {
 GenerateErrorLogs() {
 	local file=$1
 	
-	if [ ! -f $file ]; then
-		touch $file
-	fi
-
 	if [ ${#errors[@]} -gt 0 ]; then
+		if [ ! -f $file ]; then
+			touch $file
+		fi
+
 		printf "%s\n" "${errors[@]}" > $file
 	fi
 }
@@ -265,20 +422,21 @@ ${commandName} -p 2222 -n 192.168.0.1/24 -u username1,sshuser@ip:port -g group1,
 ${whiitebold}Parameters :${gray}
     -p  --ssh-port     : SSH port
     -n  --network-host : Network host
+
     -u  --allow-users  : Allowed users to connect through SSH
     -g  --allow-groups : Allowed groups to connect through SSH
     -U  --deny-users   : Denied users to connect through SSH
     -G  --deny-groups  : Denied groups to connect through SSH
+
+	--verbose          : Display logs
+	--silent           : Don't display logs
+
     -h  --help         : show this message
 ${nocolor}\n"
 }
 
 ## ------------------------------------------------------------------------------------------------------------------------------------ ##
 
-# CheckIfRoot
-if [[ silent = false ]]; then
-	StartText
-fi
 # Récupération des paramètres en utilisant getopts
 while [[ $# -gt 0 ]]; do
   case $1 in
@@ -306,11 +464,16 @@ while [[ $# -gt 0 ]]; do
       	shift
       	denied_groups=($(echo "$1" | tr ',' ' '))
       	;;
+	--verbose)
+		shift
+		verbose=true
+		;;
 	--silent)
 		shift
 		silent=true
 		;;
-    -h | --help)
+	-h | --help)
+		StartText
 		HowToUse
 		exit 0
 		;;
@@ -322,14 +485,22 @@ while [[ $# -gt 0 ]]; do
   shift
 done
 
+# CheckIfRoot
+if [[ $silent == false ]]; then
+	clear
+	StartText
+fi
+
 CheckMandatoryParams
 
 if [[ "${#allowed_users[@]}" -gt 0 ]]; then
-	printf "${blue}Checking allow users ...${nocolor}\n"
+	if [ $silent == false ]; then
+		printf "${blue}Checking allow users ...${nocolor}\n"
+	fi
 	CheckAllowUsers
 	ManageAllowUsers
-else
-	printf "no allowed users to treate\n"
+elif [ $verbose == true ]; then
+	printf "${c__notice}no allowed users to manage${nocolor}\n"
 fi
 
 
@@ -337,26 +508,31 @@ if [[ "${#allowed_groups[@]}" -gt 0 ]]; then
 	printf "${blue}Checking allow groups ...${nocolor}\n"
 	CheckAllowGroups
 	ManageAllowGroups
-else
-	printf "no allowed groups to treate\n"
+elif [ $verbose == true ]; then
+	printf "${c__notice}no allowed groups to create${nocolor}\n"
 fi
 
 if [[ "${#denied_users[@]}" -gt 0 ]]; then
 	printf "${blue}Checking denied users ...${nocolor}\n"
 	CheckDeniedUsers
 	ManageDeniedUsers
-else
-	printf "no denied groups to treate\n"
+elif [ $verbose == true ]; then
+	printf "${c__notice}no denied users to create${nocolor}\n"
 fi
 
 if [[ "${#denied_groups[@]}" -gt 0 ]]; then
 	printf "${blue}Checking denied groups ...${nocolor}\n"
 	CheckDeniedGroups
 	ManageDeniedGroups
-else
-	printf "no denied groups to treate\n"
+elif [ $verbose == true ]; then
+	printf "${c__notice}no denied groups to create${nocolor}\n"
 fi
 
-GenerateErrorLogs $actualpwd/logs/init-ssh-error.log
+printf "\n"
+ManageSSH
+printf "\n"
+ManageNetwork
+
+# GenerateErrorLogs $actualpwd/logs/init-ssh-error.log
 
 exit 0
diff --git a/scripts/init-users b/scripts/init-users
--- a/scripts/init-users
+++ b/scripts/init-users
@@ -1,7 +1,10 @@
 #!/bin/bash
 
-# create a script to add users to groups
-# add-user-to-group group1:username1,username2,group2:username3,username4
+# if [ "$EUID" -ne 0 ]; then
+# 	printf "${red}Please run this script as root.${nocolor}\n"
+# 	g_errors+=("Run this script as root")
+# 	exit 1
+# fi
 
 ############
 ## COLORS ##
@@ -29,41 +32,89 @@ c__fctAction=$graydim
 c__fct2=$gray
 c__msgVar=$graybold
 c__value=$blue
+c__value2=$purple
 c__error=$red
 c__warning=$orange
 c__success=$green
 
 
 ## VARIABLES
+repSkell="files/etc/skel"
 pwd=$(pwd)
 actualpwd=$(pwd)
-
-errors=()
+g_errors=()
 
 ###############
 ## PARAMETERS
 ###############
 commandPath=$0
 commandName=`basename "$commandPath"`
-groupstring=
+create=false
+delete=false
+groupstring=""
 silent=false
+verbose=false
 
 ##############
 ## FUNCTIONS
 ##############
-GenerateErrorLogs() {
-	local file=$1
-	
-	if [ ! -f $file ]; then
-		touch $file
-	fi
 
-	if [ ${#errors[@]} -gt 0 ]; then
-		printf "%s\n" "${errors[@]}" > $file
-	fi
+ManageSkelFiles() {
+	printf "${c__fctName}Load skel files${nocolor}\n"
+
+	find "$repSkell" -type f | while read -r file; do
+		local filename=$(basename "$file")
+		
+		printf "  ${c__fctAction}/etc/skel/${c__msgVar}${filename}"
+		if [ -f "/etc/skel/$filename" ]; then
+			printf "${c__fctAction} ...${nocolor}"
+
+			mv "/etc/skel/$filename" "/etc/skel/$filename.bak" > /dev/null 2>&1
+			local result=$?
+			if [ $result -eq 0 ]; then
+				printf "${c__success} saved${nocolor}"
+			else
+				printf "${c__error} save failed${nocolor}"
+				g_errors+=("renamed failed")
+			fi
+		else
+			printf "\n   ${yellow}not found ${c__fctAction}in ${c__fct2}/etc/skel${nocolor}"
+		fi
+		cp "files/etc/skel/$filename" "/etc/skel/$filename" > /dev/null 2>&1
+		result=$?
+		if [ $result -eq 0 ]; then
+			printf "${c__fctAction} - ${c__success}copied${nocolor}\n"
+		else
+			printf "${c__fctAction} - ${c__error}copy failed${nocolor}\n"
+			g_errors+=("Failed to copy /etc/skel/$filename")
+		fi
+	done
+	
+	# find "$repSkell" -type f | while read -r file; do
+	# 	local filename=$(basename "$file")
+	# 	if [ -f "/etc/skel/$filename" ]; then
+	# 		printf "  ${c__fctAction}Copying  ${c__msgVar}${filename} ${c__fctAction}...${nocolor}"
+	# 		cp "/etc/skel/$filename" "/etc/skel/$filename" # > /dev/null 2>&1
+	# 		local result=$?
+	# 		if [ $result -eq 0 ]; then
+	# 			printf "${c__success} done${nocolor}\n"
+	# 		else
+	# 			printf "${c__error} failed${nocolor}\n"
+	# 			g_errors+=("Failed to copy /etc/skel/$filename")
+	# 		fi
+	# 	else
+	# 		printf "  ${c__fctAction}File ${c__msgVar}${filename} ${c__warning}not found${nocolor}\n"
+	# 	fi
+	# done
 }
 
-
+CheckIfParameters() {
+	if [ $create == false ] && [ $delete == false ] && [ -z "$groupstring" ] && [ $silent == false ]; then
+		return 1
+	else
+		return 0
+	fi
+}
 CheckMandatoryParams() {
 	if [ -z "$groupstring" ]; then
 		printf "${c__error}parameter ${c__msgVar}-g | --groups${c__error} is mandatory.${nocolor}\n"
@@ -73,123 +124,231 @@ CheckMandatoryParams() {
 
 CheckIfUserExists() {
 	local user=$1
-	printf "${c__fctName}Checking user $user ...${nocolor}\n"
+	# printf "${c__fctAction}Checking user ${c__msgVar}${user}${c__fctAction} ...${nocolor}\n"
+	printf "   ${c__fctAction}${c__msgVar}${user}${c__fctAction} ...${nocolor}"
 	getent passwd $user > /dev/null 2>&1
-	if [ $? -eq 0 ]; then
-		printf "${c__success}user ${whiitebold}$user${c__success} exist${nocolor}\n"
+	local result=$?
+	if [ $result -eq 0 ]; then
+		printf "${c__success} found${nocolor}\n"
 		return 0
 	else
-		printf "${c__warning}user ${whiitebold}$user${c__warning} not exist${nocolor}\n"
+		printf "${c__warning} not found${nocolor}\n"
 		return 1
 	fi
 }
 CheckIfGroupExists() {
 	local group=$1
-	printf "${c__fctName}Checking group $group ...${nocolor}\n"
+	# printf "${c__fctAction}Checking group ${c__msgVar}${group}${c__fctAction} ...${nocolor}"
+	printf "  ${c__fctAction}${c__msgVar}${group}${c__fctAction} ...${nocolor}"
 	getent group $group > /dev/null 2>&1
-	if [ $? -eq 0 ]; then
-		printf "${c__success}group ${whiitebold}$group${c__success} exist${nocolor}\n"
+	local result=$?
+	if [ $result -eq 0 ]; then
+		printf "${c__success} found${nocolor}\n"
 		return 0
 	else
-		printf "${c__warning}group ${whiitebold}$group${c__warning} not exist${nocolor}\n"
+		printf "${c__warning} not found${nocolor}\n"
 		return 1
 	fi
 }
 
 
 
+
+
 Main() {
-	IFS='/' read -r -a groups <<< "${groupstring}"
-	
+	printf "${c__fctName}Start login creation ...${nocolor}\n"
+
+	local cptGroupsCreated=0
+	local cptUsersCreated=0
+
+	IFS=';' read -r -a groups <<< "${groupstring}"
+
 	for grp in "${groups[@]}"; do
 		local groupCreated=false
-		local groupName=$(echo "$grp" | cut -d':' -f1)
-		local users=$(echo "$grp" | cut -d':' -f2)
-		IFS=',' read -r -a usernames <<< "${users}"
-
-		printf "${c__fctName}Group: ${c__value}${groupName}${nocolor}\n"
-
-		## GROUP CREATION
-		CheckIfGroupExists $groupName
-		if [ $? -eq 1 ]; then
-			printf "${c__fctAction}Creating group ${c__msgVar}${groupName}${c__fctAction} ... ${nocolor}"
-			addgroup $groupName > /dev/null 2>&1
-			if [ $? -eq 0 ]; then
-				printf "${c__success}added${nocolor}\n"
-				groupCreated=true
-			else
-				printf "${c__error}failed${nocolor}\n"
-				groupCreated=false
-				errors+=("Group $groupName not created")
-			fi
+		IFS='=' read -r -a a_grp <<< "${grp}"
+		local groupName=${a_grp[0]}
+		local users=${a_grp[1]}
+		
+		if [[ $silent == false ]]; then
+			printf "${c__fctName}Group: ${c__value}${groupName}${nocolor}\n"
 		fi
 
-		printf "\n${c__fctName}Users: ${c__value}${usernames[*]}${nocolor}\n"
-		# ## FOR each USERNAMES
-		for usrname in "${usernames[@]}"; do
-			local userCreated=false
+
+		CheckIfGroupExists $groupName
+		local grpExists=$?
+		if [ $grpExists -eq 1 ]; then
+			if [[ $silent == false ]]; then
+				printf "  ${c__fctAction}Creating ${c__value}${groupName}${c__fctAction} ...${nocolor}"
+			fi
+			## GROUP CREATION
+			groupadd $groupName > /dev/null 2>&1
+			local grpadded=$?
+			if [ $grpadded -eq 0 ]; then
+				if [[ $silent == false ]]; then
+					printf "${c__success} done${nocolor}\n"
+				fi
+				groupCreated=true
+				cptGroupsCreated=$((cptGroupsCreated+1))
+			else
+				if [[ $silent == false ]]; then
+					printf "${c__error} failed${nocolor}\n"
+				fi
+				groupCreated=false
+				g_errors+=("Group $groupName not created")
+			fi
+		else
+			groupCreated=false
+		fi
+
+		if [[ -z "$users" ]]; then
+			if [[ $verbose == true ]]; then
+				printf "${c__fctAction}No users to create${nocolor}\n"
+			fi
+			continue
+		fi
+		IFS=',' read -r -a usernames <<< "${users}"
+
+		if [[ $silent == false ]]; then
+			printf "  ${c__fctName}Users: ${nocolor}"
+			for usrln in "${usernames[@]}"; do
+				local usrnm=$(echo "$usrln" | cut -d'/' -f1)
+				printf "${c__value}${usrnm} ${nocolor}"
+			done
+			printf "\n"
+		fi
+
+		local l_cptUsersCreated=0
+		local l_cptUsersAdded=0
+		for username in "${usernames[@]}"; do
+			userCreated=false
 			
-			## USER CREATION
-			CheckIfUserExists $usrname
-			if [ $? -eq 1 ]; then
-				printf "${c__fctAction}Creating user ${c__msgVar}${usrname}${c__fctAction} ... ${nocolor}"
-				adduser $usrname > /dev/null 2>&1
-				if [ $? -eq 0 ]; then
-					printf "${c__success}added${nocolor}\n"
+			CheckIfUserExists $username
+			local usrExists=$?
+			if [ $usrExists -eq 1 ]; then
+				if [[ $silent == false ]]; then
+					printf "   ${c__fctAction}creating ${c__value}${username}${c__fctAction} ...${nocolor}"
+				fi
+
+				## USER CREATION
+				useradd --create-home $username -G $groupName > /dev/null 2>&1
+				local usradded=$?
+				if [ $usradded -eq 0 ]; then
+					if [[ $silent == false ]]; then
+						printf " ${c__success}done${nocolor}\n"
+						l_cptUsersCreated=$((l_cptUsersCreated+1))
+					fi
 					userCreated=true
+					usrExists=1
 				else
-					printf "${c__error}failed${nocolor}\n"
+					if [[ $silent == false ]]; then
+						printf " ${c__error}failed${nocolor}\n"
+					fi
 					userCreated=false
-					errors+=("User $usrname not created")
+					g_errors+=("User $username not created")
 				fi
 			else
-				userCreated=false
+				# Retrieve the list of groups the user belongs to
+				grps=$(id -nG "$username")
+				# Check if the desired group exists in the list
+				if [[ "$grps" =~ (^| )"$groupName"($| ) ]]; then
+					printf "   ${c__msgVar}${username} ${c__fctAction}already in ${c__msgVar}${groupName}${c__fctAction}${nocolor}\n"
+				else
+					printf "   ${c__fctAction}Inserting ${c__msgVar}${username} ${c__fctAction}to ${c__msgVar}${groupName}${c__fctAction} ...${nocolor}"
+					# sudo usermod -aG ${groupName} ${username} > /dev/null 2>&1
+					usermod -aG ${groupName} ${username}
+					local usrgrp=$?
+					if [ $? -eq 0 ]; then
+						l_cptUsersAdded=$((l_cptUsersAdded+1))
+						printf " ${c__success}done${nocolor}"
+					else
+						printf " ${c__error}failed${nocolor}"
+						g_errors+=("User $username not added to group $groupName")
+					fi
+					printf "\n"
+				fi
+
+
+				# # add user to group
+				# if [[ $silent == false ]]; then
+				# 	printf "   ${c__fctAction}user ${c__value}${username}${c__fctAction} already exists${nocolor}\n"
+				# fi
+
+				# printf "   ${c__fctAction}Inserting user ${c__msgVar}${username} ${c__fctAction}to group ${c__msgVar}${groupName}${c__fctAction} ...${nocolor}"
+				# sudo usermod -aG ${groupName} ${username} > /dev/null 2>&1
+				# local usrgrp=$?
+				# if [ $? -eq 0 ]; then
+				# 	l_cptUsersAdded=$((l_cptUsersAdded+1))
+				# 	printf " ${c__success}added${nocolor}\n"
+				# else
+				# 	printf " ${c__error}failed${nocolor}\n"
+				# 	g_errors+=("User $username not added to group $groupName")
+				# fi
 			fi
 
-			## ADD USER to GROUP
-			if [ $userCreated != true ]; then
-				continue;
-			else
-				printf "${c__fctAction}Inserting user ${c__msgVar}${usrname}${c__fctAction} to group ${c__msgVar}${groupName}${c__fctAction} ... ${nocolor}"
-				sudo usermod -aG ${groupName} ${usrname} > /dev/null 2>&1
-				if [ $? -eq 0 ]; then
-					printf "${c__success}added${nocolor}\n"
-					# return 0
-				else
-					printf "${c__error}failed${nocolor}\n"
-					errors+=("User $usrname not added to group $groupName")
-					# return 1
-				fi
-			fi
+
+			# ## ADD USER to GROUP
+			# if [ $usrExists -eq 1 ] || [ $userCreated == true ]; then
+			# 	printf "   ${c__fctAction}Inserting user ${c__msgVar}${username} ${c__fctAction}to group ${c__msgVar}${groupName}${c__fctAction} ...${nocolor}"
+			# 	# sudo usermod -aG ${groupName} ${username} > /dev/null 2>&1
+			# 	usermod -aG ${groupName} ${username}
+			# 	local usrgrp=$?
+			# 	if [ $? -eq 0 ]; then
+			# 		l_cptUsersAdded=$((l_cptUsersAdded+1))
+			# 		printf " ${c__success}added${nocolor}"
+			# 	else
+			# 		printf " ${c__error}failed${nocolor}"
+			# 		g_errors+=("User $username not added to group $groupName")
+			# 	fi
+			# 	printf "\n"
+			# fi
 
 		done
+
+		cptUsersCreated=$((cptUsersCreated+l_cptUsersCreated))
+
+		if [ $silent == false ] && ([ $l_cptUsersCreated -gt 0 ] || [ $l_cptUsersAdded -gt 0 ]); then
+			printf "${c__success}${groupName}${c__fct2}\n"
+			printf "  ${c__value}${l_cptUsersCreated}${c__fct2} user(s) created\n"
+			printf "  ${c__value}${l_cptUsersAdded}${c__fct2} user(s) added${nocolor}\n"
+			printf "\n"
+		fi
 	done
+
+	if [ $silent == false ] && ([ $cptGroupsCreated -gt 0 ] || [ $cptUsersCreated -gt 0 ]); then
+		printf "${c__fctName}Summary${c__fct2}\n"
+		printf "  ${c__value}${cptGroupsCreated}${c__fct2} group(s) created\n"
+		printf "  ${c__value}${cptUsersCreated}${c__fct2} user(s) created${nocolor}\n"
+		# if [ ${#g_errors[@]} -eq 0 ]; then
+		# 	for err in "${g_errors[@]}"; do
+		# 		printf "  ${c__error}• ${err}${nocolor}\n"
+		# 	done
+		# fi
+		printf "\n"
+	fi
 }
 
 StartText () {
-printf "🔐 ${blue}$commandName script ${nocolor}🔐
-
-${whiitebold}This script is made to create users and groups${nocolor}
-\n"
+	printf "🔐 ${blue}$commandName script ${nocolor}🔐
+	\n"
 }
 HowToUse() {
-printf "❓ ${blue}How to use${gray}
-
-${commandName} --create -g group1:username1,sshuser@ip:port/group2:username3,username4${nocolor}
-
-${whiitebold}Parameters :${gray}
-	--create             : Flag to for creation
-	--delete             : Flag to delete
-    -g  --groups : Allowed groups to connect through SSH
-				(format: --allowed-groups group1:username1,username2/group2:username3,username4)
-    -h  --help          : show this message
-${nocolor}\n"
+	printf "❓ ${blue}How to use${gray}\n"
+	printf "${whiitebold}This script is made to create users and groups${nocolor}\n"
+	printf "\n"
+	printf "${commandName} --groups \"group1=username1,sshuser@ip:port/group2=username3,username1\"${nocolor}"
+	printf "\n"
+	printf "${whiitebold}Parameters :${gray}\n"
+	printf "  -g  --groups : groups to add users\n"
+	printf "                 format: group1=username1,username2;group2=username3,username1\n"
+	printf "  --verbose    : show logs\n"
+	printf "  --silent     : hide logs\n"
+	printf "\n"
+	printf "  -h  --help   : show this message\n"
+	printf "${nocolor}\n"
 }
 
 ## -----------------------------------------------------------------------
-if [[ silent = false ]]; then
-	StartText
-fi
+
 # Récupération des paramètres en utilisant getopts
 while [[ $# -gt 0 ]]; do
   case $1 in
@@ -206,7 +365,10 @@ while [[ $# -gt 0 ]]; do
 	--silent)
 	  silent=true
 	  ;;
-    -h | --help)
+    --verbose)
+	  verbose=true
+	  ;;
+	-h | --help)
 	HowToUse
 	exit 0
 		;;
@@ -218,12 +380,26 @@ while [[ $# -gt 0 ]]; do
   shift
 done
 
+CheckIfParameters
+if [ $? -eq 1 ]; then
+	StartText
+	HowToUse
+	exit 1
+fi
+
+if [[ $silent == false ]]; then
+	StartText
+fi
+
+
 CheckMandatoryParams
 if [ $? -eq 1 ]; then
 	# HowToUse
 	exit 1
 fi
 
+ManageSkelFiles
+if [[ $silent == false ]]; then
+	printf "\n"
+fi
 Main
-
-GenerateErrorLogs $actualpwd/logs/init-users-error.log
diff --git a/scripts/prox-install b/scripts/prox-install
--- a/scripts/prox-install
+++ b/scripts/prox-install
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+if [ "$EUID" -ne 0 ]; then
+	printf "${red}Please run this script as root.${nocolor}\n"
+	errors+=("Run this script as root")
+	exit 1
+fi
+
 ############
 ## COLORS ##
 ############
@@ -61,7 +67,7 @@ LoadConfig(){
 	. ./prox.conf
 
 	if [ $proxmox == false ] && [ $init_iptables == false ] && [ $init_users == false ] && [ $init_ssh == false ]; then
-		printf "${orange}No action requested. In ${whiitebold}prox.conf${orange}, enable at least one ${whiitebold}init_*${orange} parameter${nocolor}\n"
+		printf "${orange}No action parameter active. In ${whiitebold}prox.conf${orange}, enable at least one ${whiitebold}init_*${orange} parameter${nocolor}\n"
 		exit 1
 	else
 		printf "${c__success}Configuration loaded${nocolor}\n"
@@ -120,7 +126,7 @@ InitUsers() {
 	printf "${c__fctName}Users initialization${nocolor}"
 	if [ $init_users == true ]; then
 		printf "\n"
-		bash init-users --create -g $groups_str
+		bash init-users --groups $groups_str
 		if [ $? -eq 1 ]; then
 			printf "${c__error}user ${whiitebold}$user${c__error} not exist${nocolor}\n"
 			return 1
@@ -204,27 +210,27 @@ Main(){
 	## > USERS INITIALIZATION
 	InitUsers
 	if [ $? -eq 1 ]; then
-		# printf "${c__error}Users initialization failed${nocolor}\n"
+		printf "${c__error}Users initialization failed${nocolor}\n"
 		return 1
 	fi
 	printf "\n"
 	## < USERS INITIALIZATION
 
-	## > SSH CONFIG
-	InitSSH
-	if [ $? -eq 1 ]; then
-		# printf "${c__error}SSH initialization failed${nocolor}\n"
-		return 1
-	fi
-	## < SSH CONFIG
+	# ## > SSH CONFIG
+	# InitSSH
+	# if [ $? -eq 1 ]; then
+	# 	printf "${c__error}SSH initialization failed${nocolor}\n"
+	# 	return 1
+	# fi
+	# ## < SSH CONFIG
 
-	## > IPTABLES CONFIG
-	InitIptables
-	if [ $? -eq 1 ]; then
-		# printf "${c__error}Iptables initialization failed${nocolor}\n"
-		return 1
-	fi
-	## < IPTABLES CONFIG
+	# ## > IPTABLES CONFIG
+	# InitIptables
+	# if [ $? -eq 1 ]; then
+	# 	printf "${c__error}Iptables initialization failed${nocolor}\n"
+	# 	return 1
+	# fi
+	# ## < IPTABLES CONFIG
 }
 
 StartText () {
diff --git a/scripts/update-ssh-config b/scripts/update-ssh-config
--- a/scripts/update-ssh-config
+++ b/scripts/update-ssh-config
@@ -46,6 +46,7 @@ runningAsRoot=false
 sshdExists=false
 syntaxStatus='invalid'
 verbose=false
+silent=false
 
 
 
@@ -53,6 +54,8 @@ verbose=false
 ## FUNCTIONS ##
 ###############
 CheckMandatoryParams() {
+	local isError=false
+
 	if [[ $verbose = true ]]; then
 		printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
 	fi
@@ -74,7 +77,7 @@ CheckMandatoryParams() {
 	
 	if [[ -z $ARG_KEY ]]; then
 		printf "${c__error}parameter ${c__msgVar}-k | --key${c__error} is mandatory.${nocolor}\n"
-		exit 1
+		isError=true
 	else
 
 		if [[ $verbose = true ]]; then
@@ -89,12 +92,16 @@ CheckMandatoryParams() {
 
 	if [[ -z $ARG_VALUE ]]; then
 		printf "${c__error}parameter ${c__msgVar}-v | --value${c__error} is mandatory.${nocolor}\n"
-		exit 1
+		isError=true
 	else
 		
 		if [[ $verbose = true ]]; then
 			printf "${c__fct2}value : ${c__value}${ARG_VALUE}${nocolor}\n"
 		fi
+	fi
+
+	if [[ $isError = true ]]; then
+		exit 1
 	fi
 }
 
@@ -141,7 +148,7 @@ update_sshd_config() {
 
 		# Check if the sed command added a new line
 		if ! grep -q "${key} ${value}" "$ARG_FILE"; then
-			printf "${gray}Key not found.${graydim}${ARG_FILE}${nocolor}\n"
+			printf "${gray}Key not found${graydim} ${ARG_FILE}${nocolor}\n"
 
 			if [ $syntaxStatus = 'unknown' ]; then
 				printf "\n# TO VALIDATE\n${key} ${value}\n" >> "$ARG_FILE"
@@ -173,7 +180,7 @@ ${whiitebold}This script is made for updating SSH configuration${nocolor}\n"
 }
 HowToUse () {
 printf "\n❓ ${blue}How to use${gray}
-${white}${commandName} -k <key> -v <value>${nocolor}\n"
+${white}${commandName} -k <key> -v <value> --verbose --silent${nocolor}\n"
 }
 
 #####
@@ -195,12 +202,6 @@ ${white}${commandName} -k <key> -v <value>${nocolor}\n"
 # else
 # 	sshdExists=true
 # fi
-
-if [[ $# -le 0 ]]; then
-	commandName=$0
-else
-	commandName="ssh-config"
-fi 
 
 # Récupération des paramètres en utilisant getopts
 while [[ $# -gt 0 ]]; do
@@ -225,6 +226,9 @@ while [[ $# -gt 0 ]]; do
 		--verbose)
 			verbose=true
 			;;
+		--silent)
+			slient=true
+			;;
 		*)
 			echo "$commandName - Option invalide: $1"
 			exit 1
@@ -240,11 +244,13 @@ CheckMandatoryParams
 validate_key_syntax "$ARG_KEY" "$ARG_VALUE"
 isValid=$?
 if [ $isValid -eq 1 ]; then
-	printf "${graydim}Cancel update.${nocolor}\n"
+	if [ $silent == false ]; then
+		printf "${graydim}Cancel update.${nocolor}\n"
+	fi
 	exit 0;
 	return
-elif [ $isValid -eq 2 ]; then
-	printf "${orange}Cannot validate syntax. ${graydim}Skip parameters validation.${nocolor}\n"
+elif [ $isValid -eq 2 ] && [ $silent == false ]; then
+	printf "${orange}Cannot validate syntax. ${graydim}Skip.${nocolor}\n"
 fi
 
 update_sshd_config "$ARG_KEY" "$ARG_VALUE"
