update-ssh-config : WIP: check for logic to append users

diff --git a/scripts/init-ssh b/scripts/init-ssh
--- a/scripts/init-ssh
+++ b/scripts/init-ssh
@@ -59,10 +59,15 @@ denied_groups=()
 existing_denied_groups=()
 
 
-##############
+##########################################
 ## VARIABLES
-##############
-sshd_config="../files/etc/ssh/sshd_config"
+##########################################
+## EDITABLES (does match with system file)
+# sshd_config="../files/etc/ssh/sshd_config"
+# hosts_allow="../files/etc/hosts.allow"
+sshd_config="/etc/ssh/sshd_config"
+hosts_allow="/etc/hosts.allow"
+
 PWD=$(pwd)
 errors=()
 pwd=$(pwd)
@@ -72,8 +77,9 @@ gentenvInvalid=false
 verbose=false
 silent=false
 
+##########################################
 ## FUNCTIONS
-
+##########################################
 function join_by {
   local d=${1-} f=${2-}
   if shift 2; then
@@ -128,9 +134,7 @@ CheckMandatoryParams() {
 		exit 1
 	else
 		if [ $verbose == true ] && [ $silent == false ]; then
-printf "
-  ${c__success}Mandatory parameters OK${nocolor}
-"
+			printf "\n  ${c__success}Mandatory parameters OK${nocolor}\n"
 		fi
 	fi
 }
@@ -149,10 +153,13 @@ CheckIfItemExists() {
 		fi
 		return 2
 	else
+		if [ $verbose == true ]; then
+			printf "${c__fctAction}command getenv found${nocolor}\n"
+		fi
 		gentenvInvalid=false
 	fi
 
-	printf "   ${c__fctAction}${c__msgVar}${item}${c__fctAction} ...${nocolor}"
+	printf "   ${c__msgVar}${item}${c__fctAction} ...${nocolor}"
 	getent passwd $item > /dev/null 2>&1
 	local result=$?
 	if [ $result -eq 0 ]; then
@@ -165,14 +172,38 @@ CheckIfItemExists() {
 }
 
 
-
+CheckAllowUsers() {
+	for usr in "${allowed_users[@]}"; do
+		if [ $gentenvInvalid == false ]; then
+			CheckIfItemExists $usr
+			local test=$?
+			if [ $test -eq 0 ]; then
+				existing_allowed_users+=("$usr")
+			elif [ $test -eq 2 ]; then
+				if [ $silent == false ]; then
+					printf "${c__warning}check for \"${usr}\" fail${nocolor}\n"
+				fi
+			fi
+		else
+			if [ $silent == false ]; then
+				printf "${c__notice}check skip for ${whiitebold}\"${usr}\"${nocolor}\n"
+			fi
+		fi
+	done
+}
 ManageAllowUsers() {
 	if [[ ${#existing_allowed_users[@]} -gt 0 ]]; then
 		if [ $silent == false ]; then
 			printf "${c__fctName}Manage allowed users ...${nocolor}\n"
 		fi
-		
-		bash ./update-ssh-config -k AllowUsers -v $(join_by , "${existing_allowed_users[@]}")
+
+		if [ $silent == true ]; then
+			bash ./update-config -k AllowUsers -v $(join_by , "${existing_allowed_users[@]}") -f "$sshd_config" --silent
+		elif [ $verbose == true ]; then
+			bash ./update-config -k AllowUsers -v $(join_by , "${existing_allowed_users[@]}") -f "$sshd_config" --verbose
+		else
+			bash ./update-config -k AllowUsers -v $(join_by , "${existing_allowed_users[@]}") -f "$sshd_config"
+		fi
 	else
 		if [ $silent == false ]; then
 			printf "${c__fctAction}No existing allowed users to manage${nocolor}\n"
@@ -206,7 +237,7 @@ ManageAllowGroups() {
 			printf "${c__fctName}Manage allowed groups ...${nocolor}\n"
 		fi
 
-		bash ./update-ssh-config -k AllowGroups -v $(join_by , "${existing_allowed_groups[@]}")
+		bash ./update-config -k AllowGroups -v $(join_by , "${existing_allowed_groups[@]}")
 	else
 		if [ $silent == false ]; then
 			printf "${c__fctAction}No existing allowed groups to manage${nocolor}\n"
@@ -240,7 +271,7 @@ ManageDeniedUsers() {
 			printf "${c__fctName}Manage denied users ...${nocolor}\n"
 		fi
 		
-		bash ./update-ssh-config -k DenyUsers -v $(join_by , "${existing_denied_users[@]}")
+		bash ./update-config -k DenyUsers -v $(join_by , "${existing_denied_users[@]}")
 	else
 		if [ $silent == false ]; then
 			printf "${c__fctAction}No existing denied users to manage${nocolor}\n"
@@ -274,7 +305,7 @@ ManageDeniedGroups() {
 			printf "${c__fctName}Manage denied groups ...${nocolor}\n"
 		fi
 
-		bash ./update-ssh-config -k DenyGroups -v $(join_by , "${existing_denied_groups[@]}")
+		bash ./update-config -k DenyGroups -v $(join_by , "${existing_denied_groups[@]}")
 	else
 		if [ $silent == false ]; then
 			printf "${c__fctAction}No existing denied groups to manage${nocolor}\n"
@@ -287,18 +318,23 @@ ManageDeniedGroups() {
 ## SSH
 ########
 ManageSSH() {
-	if [ $silent == false ]; then
-		printf "${c__fctName}Update ssh port ...${nocolor}\n"
+	if [[ -z $ssh_port ]]; then
+		return 0
 	fi
 
-	if [ $silent == true ] && [ $verbose == true ]; then
-		bash ./update-ssh-config -k Port -v $ssh_port --verbose --silent
-	elif [ $silent == true ]; then
-		bash ./update-ssh-config -k Port -v $ssh_port --silent
+	if [ $silent == false ]; then
+		printf "\n${c__fctName}Update ssh port...${nocolor}\n"
+	fi
+
+	# if [ $silent == true ] && [ $verbose == true ]; then
+	# 	bash ./update-config -k Port -v $ssh_port --verbose --silent
+	# elif [ $silent == true ]; then
+	if [ $silent == true ]; then
+		bash ./update-config -k Port -v $ssh_port -f "$sshd_config" --silent
 	elif [ $verbose == true ]; then
-		bash ./update-ssh-config -k Port -v $ssh_port --verbose
+		bash ./update-config -k Port -v $ssh_port -f "$sshd_config" --verbose
 	else
-		bash ./update-ssh-config -k Port -v $ssh_port
+		bash ./update-config -k Port -v $ssh_port -f "$sshd_config"
 	fi
 }
 
@@ -306,28 +342,46 @@ ManageSSH() {
 ## NETWORK
 ########
 ManageNetwork() {
-	if [ $silent == false ]; then
-		printf "${c__fctName}Manage network ...${nocolor}\n"
+	if [[ -z $network_cidr ]]; then
+		return 0
 	fi
 
-	if [ -f "/etc/hosts.allow" ]; then
-		echo "sshd: 10.10.200.0/24 : ALLOW" >> "/etc/hosts.allow"
-		if [ $silent == false ]; then
-			printf "${c__success}file \"/etc/hosts.allow\" updated${nocolor}\n"
+	if [ $silent == false ]; then
+		printf "\n${c__fctName}Manage network ...${nocolor}\n"
+	fi
+
+	if [ -f "$hosts_allow" ]; then
+
+		# find in file if network_cidr already exists
+		local found=$(grep -c "$network_cidr" "$hosts_allow")
+		if [ $found -eq 0 ]; then
+			if [ $silent == false ]; then
+				printf "${c__fctAction}Add network_cidr ${c__value}${network_cidr}${nocolor} to ${c__msgVar}${hosts_allow}${nocolor}\n"
+			fi
+			echo "sshd: $network_cidr : ALLOW" >> "$hosts_allow"
+		else
+			if [ $silent == false ]; then
+				printf "${c__fctAction}Network_cidr ${c__value}${network_cidr}${nocolor} already exists in ${c__msgVar}${hosts_allow}${nocolor}\n"
+			fi
 		fi
+
+		# echo "sshd: $network_cidr : ALLOW" >> "$hosts_allow"
+		# if [ $silent == false ]; then
+		# 	printf "${c__success}file \"$hosts_allow\" updated${nocolor}\n"
+		# fi
 	else
 		if [ $silent == false ]; then
-			printf "${c__error}file \"/etc/hosts.allow\" does not exists. ${graydim}Skip${nocolor}\n"
+			printf "${c__error}file \"$hosts_allow\" does not exists. ${graydim}Skip${nocolor}\n"
 		fi
 	fi
 	# if [ $silent == true ] && [ $verbose == true ]; then
-	# 	bash ./update-ssh-config -k Port -v $ssh_port --verbose --silent
+	# 	bash ./update-config -k Port -v $ssh_port --verbose --silent
 	# elif [ $silent == true ]; then
-	# 	bash ./update-ssh-config -k Port -v $ssh_port --silent
+	# 	bash ./update-config -k Port -v $ssh_port --silent
 	# elif [ $verbose == true ]; then
-	# 	bash ./update-ssh-config -k Port -v $ssh_port --verbose
+	# 	bash ./update-config -k Port -v $ssh_port --verbose
 	# else
-	# 	bash ./update-ssh-config -k Port -v $ssh_port
+	# 	bash ./update-config -k Port -v $ssh_port
 	# fi
 }
 
@@ -364,9 +418,7 @@ GenerateErrorLogs() {
 
 
 StartText () {
-# clear
-printf "🔐 ${blue}$commandName script ${nocolor}🔐
-\n"
+	printf "🔐 ${blue}$commandName script ${nocolor}🔐\n"
 }
 HowToUse() {
 	printf "❓ ${blue}How to use${gray}\n"
@@ -378,13 +430,13 @@ HowToUse() {
 	printf "${commandName} -p 2222 -n 192.168.0.1/24 -u username1,sshuser@ip:port -g group1,group2 -U username3,sshuser@ip:port -G group4${nocolor}"
 	printf "\n"
 	printf "${whiitebold}Parameters :${gray}\n"
-	printf "  -g  --ssh-port     : SSH port\n"
-	printf "  -g  --network-host : Network host\n"
+	printf "  -p  --ssh-port     : SSH port\n"
+	printf "  -n  --network-host : Network host\n"
 	printf "\n"
-	printf "  -g  --allow-users  : Allowed users to connect through SSH\n"
+	printf "  -u  --allow-users  : Allowed users to connect through SSH\n"
 	printf "  -g  --allow-groups : Allowed groups to connect through SSH\n"
-	printf "  -g  --deny-users   : Denied users to connect through SSH\n"
-	printf "  -g  --deny-groups  : Denied groups to connect through SSH\n"
+	printf "  -U  --deny-users   : Denied users to connect through SSH\n"
+	printf "  -G  --deny-groups  : Denied groups to connect through SSH\n"
 	printf "\n"
 	printf "  --verbose    : show logs\n"
 	printf "  --silent     : hide logs\n"
@@ -393,7 +445,12 @@ HowToUse() {
 	printf "${nocolor}\n"
 }
 
+
+
+
 ## ------------------------------------------------------------------------------------------------------------------------------------ ##
+
+
 
 # Récupération des paramètres en utilisant getopts
 while [[ $# -gt 0 ]]; do
@@ -454,47 +511,47 @@ if [[ $silent == false ]]; then
 	StartText
 fi
 
-CheckMandatoryParams
+# CheckMandatoryParams
+
+
+ManageSSH
+ManageNetwork
+
 
 if [[ "${#allowed_users[@]}" -gt 0 ]]; then
 	if [ $silent == false ]; then
-		printf "${blue}Checking allow users ...${nocolor}\n"
+		printf "${c__fctName}Checking allow users ...${nocolor}\n"
 	fi
 	CheckAllowUsers
 	ManageAllowUsers
-elif [ $verbose == true ]; then
-	printf "${c__notice}no allowed users to manage${nocolor}\n"
+# elif [ $verbose == true ]; then
+# 	printf "${c__fctAction}no allowed users to manage${nocolor}\n"
 fi
 
 
 if [[ "${#allowed_groups[@]}" -gt 0 ]]; then
-	printf "${blue}Checking allow groups ...${nocolor}\n"
+	printf "${c__fctName}Checking allow groups ...${nocolor}\n"
 	CheckAllowGroups
 	ManageAllowGroups
-elif [ $verbose == true ]; then
-	printf "${c__notice}no allowed groups to create${nocolor}\n"
+# elif [ $verbose == true ]; then
+# 	printf "${c__fctAction}no allowed groups to create${nocolor}\n"
 fi
 
 if [[ "${#denied_users[@]}" -gt 0 ]]; then
-	printf "${blue}Checking denied users ...${nocolor}\n"
+	printf "${c__fctName}Checking denied users ...${nocolor}\n"
 	CheckDeniedUsers
 	ManageDeniedUsers
-elif [ $verbose == true ]; then
-	printf "${c__notice}no denied users to create${nocolor}\n"
+# elif [ $verbose == true ]; then
+# 	printf "${c__fctAction}no denied users to create${nocolor}\n"
 fi
 
 if [[ "${#denied_groups[@]}" -gt 0 ]]; then
-	printf "${blue}Checking denied groups ...${nocolor}\n"
+	printf "${c__fctName}Checking denied groups ...${nocolor}\n"
 	CheckDeniedGroups
 	ManageDeniedGroups
-elif [ $verbose == true ]; then
-	printf "${c__notice}no denied groups to create${nocolor}\n"
+# elif [ $verbose == true ]; then
+# 	printf "${c__fctAction}no denied groups to create${nocolor}\n"
 fi
-
-printf "\n"
-ManageSSH
-printf "\n"
-ManageNetwork
 
 # GenerateErrorLogs $actualpwd/logs/init-ssh-error.log
 
diff --git a/scripts/update-ssh-config b/scripts/update-ssh-config
--- a/scripts/update-ssh-config
+++ b/scripts/update-ssh-config
@@ -34,9 +34,10 @@ c__success=$green
 commandPath=$0
 commandName=`basename "$commandPath"`
 # ARG_FILE="../files/etc/ssh/sshd_config"
-ARG_FILE="/etc/ssh/sshd_config"
+ARG_FILE=
 ARG_KEY=
 ARG_VALUE=
+ARG_REPLACE=false
 
 
 ##############
@@ -46,6 +47,7 @@ sshd_path="/usr/sbin/sshd"
 runningAsRoot=false
 sshdExists=false
 syntaxStatus='invalid'
+replace=false
 verbose=false
 silent=false
 
@@ -69,9 +71,6 @@ CheckMandatoryParams() {
 		printf "${c__fctName}Checking mandatory parameters ...${nocolor}\n"
 	fi
 
-	if [[ $verbose = true ]]; then
-		printf "${c__fctAction}Checking for file parameter ...${nocolor}\n"
-	fi
 	if [[ -z $ARG_FILE ]]; then
 		# printf "${c__error}ssh config file is mandatory.${nocolor}\n"
 		printf "${c__error}parameter ${c__msgVar}-f | --file${c__error} is mandatory.${nocolor}\n"
@@ -83,10 +82,6 @@ CheckMandatoryParams() {
 		fi
 	fi
 
-	if [[ $verbose = true ]]; then
-		printf "${c__fctAction}Checking for key parameter ...${nocolor}\n"
-	fi
-	
 	if [[ -z $ARG_KEY ]]; then
 		printf "${c__error}parameter ${c__msgVar}-k | --key${c__error} is mandatory.${nocolor}\n"
 		isError=true
@@ -97,10 +92,6 @@ CheckMandatoryParams() {
 		fi
 	fi
 
-
-	if [[ $verbose = true ]]; then
-		printf "${c__fctAction}Checking for value parameter ...${nocolor}\n"
-	fi
 
 	if [[ -z $ARG_VALUE ]]; then
 		printf "${c__error}parameter ${c__msgVar}-v | --value${c__error} is mandatory.${nocolor}\n"
@@ -151,21 +142,40 @@ validate_key_syntax() {
 update_sshd_config() {
     local key=$1
     local value=$2
+	local file=$3
+
+	# # transform the comma in value by a space
+	value=${value//,/ }
+
+	# check is need to append or replace
+	if [[ "$ARG_REPLACE" == false ]]; then
+		local currentval=$(grep -E "^${key}" "$file")
+		currentval=${currentval//$key/}
+		# # Supprimer les espaces de début de chaîne
+		currentval=${currentval#"${currentval%%[![:space:]]*}"}
+		currentval=${currentval%%[[:space:]]*}
+
+		echo "|$currentval|"
+		if [ -n "$currentval" ]; then
+			value=$(echo "${value} ${currentval}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
+		fi	
+	fi
 
 	# Use sed to find and replace the configuration line, even if it's commented out
 	sed -i "s/^#\?\s*${key}\s*.*/${key} ${value}/" "$ARG_FILE"
 	sedResult=$?
+
 	# Check if the sed command was successful
 	if [ $sedResult -eq 0 ]; then
 
 		# Check if the sed command added a new line
-		if ! grep -q "${key} ${value}" "$ARG_FILE"; then
-			printf "${gray}Key not found${graydim} ${ARG_FILE}${nocolor}\n"
+		if ! grep -q "${key} ${value}" "$file"; then
+			printf "${gray}Key not found${graydim} ${file}${nocolor}\n"
 
 			if [ $syntaxStatus = 'unknown' ]; then
-				printf "\n# TO VALIDATE\n${key} ${value}\n" >> "$ARG_FILE"
+				printf "\n# TO VALIDATE\n${key} ${value}\n" >> "$file"
 			elif [ $syntaxStatus = 'valid' ]; then
-				printf "\n${key} ${value}\n" >> "$ARG_FILE"
+				printf "\n${key} ${value}\n" >> "$file"
 			else
 				printf "${red}synthax invalid${nocolor}\n"
 				exit 1
@@ -173,7 +183,7 @@ update_sshd_config() {
 
 			printf "${green}Add${gray} - Set ${blue}${key} ${purple}${value}${nocolor}\n"
 		else 
-			printf "${yellow}Update${gray} - Set ${blue}${key} ${purple}${value}${gray} ${graydim}${ARG_FILE}${nocolor}\n"
+			printf "${yellow}Update${gray} - Set ${blue}${key} ${purple}${value}${gray} ${graydim}${file}${nocolor}\n"
 		fi
 
 	else
@@ -192,7 +202,7 @@ ${whiitebold}This script is made for updating SSH configuration${nocolor}\n"
 }
 HowToUse () {
 printf "\n❓ ${blue}How to use${gray}
-${white}${commandName} -k <key> -v <value> --verbose --silent${nocolor}\n"
+${white}${commandName} -k <key> -v <value> --replace --verbose --silent${nocolor}\n"
 }
 
 #####
@@ -201,7 +211,7 @@ ${white}${commandName} -k <key> -v <value> --verbose --silent${nocolor}\n"
 
 # Check if the script is being run with root privileges
 if [ "$EUID" -ne 0 ]; then
-    printf "${red}Please run this script as root.${nocolor}\n"
+    printf "${red}Please run ${c__fct2}$commandName${red} as root.${nocolor}\n"
     exit 1
 else
    runningAsRoot=true
@@ -231,6 +241,10 @@ while [[ $# -gt 0 ]]; do
 		-f | --file)
 			shift
 			ARG_FILE=$1
+			;;
+		--replace)
+			shift
+			ARG_REPLACE=true
 			;;
 		-h | --help)
 			StartText
@@ -278,4 +292,4 @@ elif [ $isValid -eq 2 ] && [ $silent == false ]; then
 	printf "${orange}Cannot validate syntax. ${graydim}Skip.${nocolor}\n"
 fi
 
-update_sshd_config "$ARG_KEY" "$ARG_VALUE"
+update_sshd_config "$ARG_KEY" "$ARG_VALUE" "$ARG_FILE"
